'use strict';function _Tt(a){if(!a||"string"!=typeof a&&!a.templ)return a;let b=_qy(a.templ?a.templ:a).nodes[0].value;for(let c of b)_dr(c);a={templ:b,regex:a.regex,flags:a.flags,ignoreCase:a.ignoreCase};1==a.templ.length&&"string"==typeof a.templ[0]&&(a=_Kk(a,a.templ[0]));return a}function _Kk(a,b){if(a.regex)try{return new RegExp(b,a.flags||(a.ignoreCase?"i":""))}catch(c){return/.^/}return a.ignoreCase?b.toUpperCase():b}
function _dr(a){if(a&&a.expr)for(let b of a.expr)if(b.args)for(a=0;a<b.args.length;++a)_dr(b.args[a]),b.args[a]=_Tt(b.args[a])}function _wy(a,b=null){if(!a||!a.templ)return a;let c="";for(let d of a.templ)c+=d.expr?_qo(d,b):d;return _Kk(a,c)}function _up(a,b=null){if(!a||!a.templ)return[a];let c=[""];for(let d of a.templ)if(d.expr){a=[];let e=_Ii(_qo(d,b));for(let f of c)for(let g of e)a.push(f+g);c=a}else for(a=0;a<c.length;++a)c[a]+=d;return c}
function _qo(a,b){let c=_ah(a.expr[0],b);for(let e=1;null!=c&&e<a.expr.length;++e){let f=a.expr[e];var d=_ap.hasOwnProperty(f.name)?function(...g){return _Jw(this)?this.map(h=>_ap[f.name].apply(h.toString?h.toString():"",g)):_ap[f.name].apply(this.toString?this.toString():"",g)}:c[f.name];c="function"==typeof d?d.apply(c,(f.args||[]).map(g=>g.expr?_qo(g,b):_wy(g))):d}return void 0===c&&1==a.expr.length?`<${a.expr[0].name}>`:null==c?"(empty)":c}
const _ap={match(a){return(this.match(a)||[""])[0]},matches(a){return this.match(a)||[]},replace(a,b){return this.replace(a instanceof RegExp?a.global?a:RegExp(a.source,"g"+a.flags):RegExp(_3a(""+a),"g"),b)},escape(){return encodeURIComponent(this).replace(/%20/g,"+")},unescape(){return unescape(this)},lines(){return this.trim().split(/\s*\n\s*/)},words(){return this.trim().split(/\s+/)},url(){return new Proxy(new String(_5w(this)),{get:_pe})}};
let _1i,_Bk,_0={},_vg={},_Pf=_we(function*(a){if(null==_0[a]){let b=yield _Vy(_2p,_Dg[a]);_0[a]="string"==typeof b?b:""}return _0[a]}),_bh=_we(function*(a){null==_vg[a]&&(_vg[a]=yield _Vy(_2f,a));return _vg[a]});
var _sp=_we(function*(a){if(!a)return a;const b=/<(\w+)>/g;let c={};a=_Ii(a);for(let d=0;d<a.length;++d){let e=a[d].match(b);if(e){for(let f of e)f=f.slice(1,-1).toLowerCase(),c.hasOwnProperty(f)||(c[f]=_Dg[f]?yield _Pf(f):yield _bh(f));a[d]=a[d].replace(b,(f,g)=>c[g.toLowerCase()])}}return 1==a.length?a[0]:a});
{let a={};var _ah=function(b,c){switch(b.name.toLowerCase()){case "clipboard":if(c=_ji(b.args,0))return _os[c]||"";_lu()&&_Lw.addFunc(_dy);return _zo.content;case "omnibox":return null==_1i&&_na[_4t]&&_Lw.addFunc(_us(function*(){null==_1i&&(_1i=yield _Vy(_nw,_na[_4t]))})),_1i||"";case "selection":return null==_Bk&&_Lw.addFunc(_us(function*(){null==_Bk&&(_Bk=(yield _qi(1E3*(+_ji(b.args,0)||.5))).content||"")})),_Bk||"";case "date":return _8h(new Date,"string"==typeof _ji(b.args,0)?b.args[0]:"Y-M-D");
case "var":return new Proxy(a,{get(d,e){if("string"!=typeof e||_Xt(e,"toString","valueOf"))return d[e];if(d.hasOwnProperty(e)){let f=d[e];delete d[e];return void 0===f?"":f}_Lw.addFunc(_us(function*(){d[e]=yield _ae("",e)}));return" "}});case "dir":return new Proxy(_0,{get(d,e){if("string"!=typeof e||_Xt(e,"toString","valueOf"))return d[e];e=e.toLowerCase();if(!_Dg[e])return"";if(d.hasOwnProperty(e))return d[e];_Lw.addFunc(_Pf(e));return" "}});case "env":return new Proxy(_vg,{get(d,e){if("string"!=
typeof e||_Xt(e,"toString","valueOf")||d.hasOwnProperty(e))return d[e];_Lw.addFunc(_bh(e));return" "}});default:return _gg(c,b.name)}}}function _Jg(){if(null!=_Kt)return _Kt;_Lw.addFunc(_us(function*(){_Kt=(yield _aj(null,_Cg(_zw).usePrevMousePos))||0}));return 0}function _go(a){return a.active&&a.highlighted?a.window.tabs.some(b=>!b.active&&b.highlighted):a.highlighted}let _kg,_Dy;
function _ys(){if(_kg)return _kg;_Dy||(_Dy=!0,_Lw.addFunc(_us(function*(){for(var a={usePrvMsPos:!!_Cg(_zw).usePrevMousePos};;){a=(yield _Vy(_No,a))||{};const b=_Kt=_Or[a.hWnd];let c=[];if("index"in a)c=yield _zg({windowId:b,index:a.index});else if("title"in a&&((c=yield _du(b,a.title))||(c=[yield d=>_Hy(b,d)]),1!=c.length)){a={x:a.x,y:a.y,getIdx:!0};continue}a.group&&c[0]&&c[0].groupId&&(c=yield _zg({windowId:b,groupId:c[0].groupId}));_kg=c.map(d=>_js(d));break}_Dy=!1})));return[]}
let _du=_we(function*(a,b){if(!b)return[];const c=500==b.length;for(;;){var d=b.replace(/\*|\?/g,"\\$&");c&&(d+="*");if((d=yield _zg({windowId:a,title:d}))&&0==d.length){let e=b.lastIndexOf(" - ");if(0<e){b=b.slice(0,e);continue}}return d}}),_3o=_we(function*(a,b){if(!b)return[];for(let d=0;;){d=b.indexOf(" - ",d+1);-1==d&&(d=void 0);var c=b.slice(0,d).replace(/\*|\?/g,"\\$&");d&&(c+="*");c=yield _zg({windowId:a,title:c});if(!d||!c||1>=c.length)return c}});
function _Hd(a){return 0<=_hd.indexOf(a)}let _Jr={};function _ke(a){if(null!=_Jr[a])return _Jr[a];_Jr[a]=null;_Jr.pending||(_Jr.pending=!0,_Lw.addFunc(_us(function*(){yield _za();delete _Jr.pending;_Jr=yield _O(Object.keys(_Jr).map(b=>+b))})));return!1}
function _gg(a,b){if(!a)return"";switch(b){case "url":return new Proxy(new String(_zh(a)),{get:_pe});case "domain":case "mainDomain":case "dirPath":case "path":return _pe(_zh(a),b);case "muted":return a.mutedInfo.muted;case "monitorId":return _wt(a.window);case "window":return new Proxy(a.window,{get(c,d){switch(d){case "underMouse":return c.id==_Jg();case "state":return _Hd(c.id)?"hidden":c.state;case "focused":return _Yw(c);case "alwaysOnTop":return _ke(c.id)}return c[d]}});case "status":return a.discarded?
"discarded":a.status;case "index":return a.index+1;case "selected":case "highlighted":return _go(a);case "openerTabId":return a.openerTabId||_Fp(a.id);case "used":return 0<=_Ft.indexOf(a.id);case "hovered":return 0<=_ys().indexOf(a.id);case "grouped":return 0<a.groupId;case "contType":return"";default:return a[b]}}function _Fp(a){if(a=_He[a])return a in _Yp?a:_Fp(a)}
function _pe(a,b){switch(b){case "protocol":return(new URL(a)).protocol;case "user":return(new URL(a)).username;case "domain":return(new URL(a)).hostname;case "mainDomain":return _Oy((new URL(a)).hostname);case "port":return(new URL(a)).port;case "path":return(new URL(a)).pathname;case "dirPath":return(new URL(a)).pathname.replace(/[^\/]+$/,"");case "query":return new Proxy(new String((new URL(a)).search),{get:_Td});case "fragment":return(new URL(a)).hash}b=a[b];"function"==typeof b&&(b=b.bind(a));
return b}function _Td(a,b){let c=a[b];"function"==typeof c?c=c.bind(a):void 0===c&&"string"==typeof b&&(a=(new URLSearchParams(a.slice(1))).getAll(b),c=1>=a.length?a[0]:a);return c}function _Oy(a){let b=a.match(/[^.]+(?:\.(?:gov|com|org|edu|net|co|mil|eu|ac|info|biz|leg|int|nom|name|gob|web))?\.(?!\d+)[^.]+$/i);return b?b[0]:a}function _sj(a,b){let c=!1,d=Object.keys(_Yp)[0],e=new Proxy(_Yp[d]||{},{get(f,g){g in f&&(!b||"url"!=g)&&(c=!0);return f[g]}});_Mt(0,()=>_wy(_Tt(a),e))(_ay);return c}
let _qy=(()=>{let a={ident:b=>({value:b}),num:b=>({value:+b}),str:b=>({value:_jf(b.slice(1,-1),"nrt'\"\\")}),regexBody:b=>({value:_jf(b.slice(1,-1),"/")}),regexFlags:b=>({value:b}),regex:()=>({value:{regex:!0},addChild(b){this.value[this.value.templ?"flags":"templ"]=b.value}}),argList:()=>({value:[],addChild(b){this.value.push(b.value)}}),exprComp:()=>({value:{},addChild(b){this.value[this.value.name?"args":"name"]=b.value}}),expr:()=>({value:{expr:[]},addChild(b){this.value.expr.push(b.value)}}),
text:b=>({value:b}),templateStr:()=>({value:[],addChild(b){"string"==typeof this.value[this.value.length-1]&&"string"==typeof b.value?this.value[this.value.length-1]+=b.value:this.value.push(b.value)}})};a.exprComp2=a.exprComp;a.text2=a.text;return _Rp({blank:/\s*/,ident:/[a-z_]\w*/i,num:/[+-]?\d+(\.\d*)?/,str:/(["'])((?!\1)[^\\]|\\.)*\1/,regexBody:/\/([^\\\/]|\\.)*\//,regexFlags:/[a-z]{1,10}/i,regex:" regexBody regexFlags? ",value:"str|regex|num|expr",argList:'"(" (value ("," value)*)? ")"',exprComp:"ident argList?",
exprComp2:'"[" value "]" argList?',expr:' exprComp ( ("." exprComp) | exprComp2 )* ',text:/[^<]+/,text2:/<[^<]*/,templateStr:' (text | ( "<" . expr . ">" ) | text2)* '},"templateStr",a)})();
