'use strict';var _Py;
{let l,k={};var _Lk=function(a,b=null,c=null,g=0){let m=a.in(_e,_t,_Bf);b={type:a,content:b};if(c){var e=2130706431*Math.random()|0;_lf(b,...m?["content"]:[]).callback=e+l}try{return d.postMessage(b),c&&(k[e]=c,g&&setTimeout(()=>q(e,_g),g)),a==_Hi&&_Lf(void 0),!0}catch(h){return c&&setTimeout(c),!1}},_Vy=(a,b,c)=>g=>_Lk(a,b,g,c);let q=function(a,b){let c=k[a];c&&(delete k[a],c(b))},w=function(){for(let a in k)q(a,"")},E=(()=>{function a(e,h){_uf(h.needed?"no-hook":"no-hook-false");g||(c||(c=setTimeout(()=>
{b=0;c=null},15E3)),5!=++b||m||(g=!0,_Lh(x=>{g=!1;_Ot(e,h.add({answer:x?"Disable notice":"Keep showing"}));_9k("noHookConflictMsg",m=x)})))}let b=0,c,g,m=_j("noHookConflictMsg");return e=>{let h=e.type;delete e.type;if("no-hook-notice"==h)a(h,e);else{if("invalidExtId"==h){if(_2u())return}else if("APDL"==h){if(_r=!0,_ul(e.result))return}else if("NH-error"==h&&3221225477==e.code){_uf("segFault");return}_Ot(h,e)}}})(),y=_ay;const z={[_Hf]:a=>{let b=_pg[a.id-_Sk+_su];if(b&&(a.trigInstId=b(a.trigInstId),
!a.trigInstId))return;a.mouseGest&&(a.trigInstId=_qt(a.trigInstId,{usePrevMousePos:a.mouseGest}));a.extEvtData&&("tabs"in a.extEvtData&&(a.extEvtData.tabs=_Dw(a.extEvtData.tabs)),a.trigInstId=_qt(a.trigInstId,a.extEvtData));_6y(16777215&a.id-_Sk,a.trigInstId)},[_5r]:a=>_bd({joysticksOrder:a.list}),[_mj]:a=>_y(a.hWnd,a.noEvt),[_Ki]:a=>_cr(a.list),[_Qg]:a=>_Wo(a.state?_td:_ik,_Or[a.hWnd]),[_9g]:a=>{_Lf(_ag(a));a.noEvt||_8o(_vt)},[_9p]:a=>q(a.id,a.params),[_fo]:a=>y(_Lj(a.actionType),a.actionSpec),[_kw]:E,
[_ef]:a=>F(a.id,a.type,a.chunk),[_R]:a=>_Ie=a.verNum,[_np]:a=>{_Jh=(_Kd=a.exeName.toLowerCase()).replace(/\.[^.]+$/,"");_Kd||_Ot("noBrwrName")},[_Pd]:_tg,[_0i]:a=>_1p(a.file,"blob")(b=>_ha(a.callback,b?b.size:_Rr)),[_jh]:a=>{}};let f={},F=(a,b,c)=>{null==f[a]&&(f[a]="list"==b?[]:"",delete f[(a+9)%20+1]);switch(b){case "text":f[a]+=c;break;case "list":f[a].push(...c);break;case "bin":f[a]+=atob(c)}};var _Yi=function(a){let b=a&&a.chunkedData;b&&(a=f[b],delete f[b]);return a},_0d=function(a,b=_ay){_Lk(_Qr,
a);b&&(y=b)};let A=function(a,b){b!=d?_Ot("rogueNatHost",{place:"msgLstnr",currPort:typeof d}):(_Jw(a)?(b=a[0],a=a[1]):(b=a.msgType,delete a.msgType),(z[b]||_ay)(a))};var _cu=a=>z.add(a),_Uj=(a,b)=>A([a,b],d),_7;let d,r,n=0,t={},u=0,v=0,p=100,B=function(a){clearTimeout(r);r=setTimeout(_Xg(),1E3*a)},C;var _Xg=_we(function*(a){_Sw();C=Date.now();d=_Yk.runtime.connectNative(_Zh[3]+"");d.onMessage.addListener(A);d.onDisconnect.addListener(c=>{c!=d?_Ot("rogueNatHost",{place:"onDisconnect",currPort:typeof d}):
(w(),c.connectSuccess&&(c=Date.now()-_dh,500>c?n=Math.min(3,n+.5):3E3<c&&(n=0),B(n)),d=null,_7=!1)});_2y=[];_Uj(_Wr);_jd=null;yield _za(p);let b=yield D();if(b){if(b==_g)p=Math.min(1E3,p+100);else if("NH0fail"==b)++v;else if("notConnected"!=b){if(5==++u){let c=Object.keys(t);1==c.length&&c[0]==_cw||_Ot("NH-startFail",{lastError:b,allErrors:c})}t[b]=!0}_Sw();a&&b.in(_g,_cw)?(yield _za(800),b=yield _Xg(a-1)):B(Math.min(8,Math.pow(Math.max(u,v)+1,.4)))}else t={},v=u=0,p=100;return!b}),_Sw=function(){clearTimeout(r);
d&&(d.disconnect(),w())};let D=_we(function*(a){86397E3<Date.now()%864E5&&(yield _za(3E3));_Sk=Date.now()/864E5|0;l=13625;let b=yield _Vy(_7s,{fileName:_xd},9E3);if(void 0===b)return"notConnected";if(b==_g)return b;if(_ul(b))return"NH0fail";d.connectSuccess=!0;_dh=Date.now();if(b)a||b!=_2e||(yield _iw("del /Q /F "+_fs),(b=yield _4u(_xd,yield _3t(_Xh,"binary")))||(b=yield D(!0)));else if(_nd?_Ye(Date.now()-C):(_Ot("NH-connect"),_Mi(["LOCAL","natHostInstalled"],_nd=!0,0)),l=parseInt(_Tj.substr(2,3),
36),f={},_Lk(_ro,{iTime:_ip,crVer:_rs,variant:_fr}),_iy(),_7=!0,yield c=>_Ry()(()=>{_oj();c()}),_Lk(_mu,{states:_ps}),yield c=>_lr(g=>_Gf(g,c)),_Lk(_zu),!G++&&!_nt("noStupEvt")){for(let c of["tabs","sess"])_iw(`forfiles /m *.${c} /d -10 /c "cmd /c del /F /Q @path"`)();_Wo(_Vs)}return b}),G=0}let _ha=(l,k)=>_Lk(_Z,{id:l,params:k});
