'use strict';var _Bg,_Md;
{let a={};var _Sa=_we(function*(b,d,c=0){let e=b.id,f=a[e]=Math.random();"normal"!=b.state&&("maximized"==b.state&&(yield _Vy(_Gs,{win:_na[e]|0})),yield _oa([e],!0),b=(yield p=>_Ms(e,!1,p))||b);let g=_8j(b);b=_Ug(_df(b),1/g);d={}.add(b,d);var l=d.x-b.x,h=d.y-b.y,m=d.w-b.w,q=d.h-b.h,k=Math.max(Math.abs(l),Math.abs(h),Math.abs(m),Math.abs(q));let r=25;c=c||r;k=Math.round(k/Math.max(1,k/c*r));const t=p=>n=>_Yk.windows.update(e,_1w(_Ug(p,-1/g)),n);if(2>=k)g=_2i(_D(d)),yield t(d);else{l/=k;h/=k;m/=k;q/=
k;r=c/k;c=-2/(k-1);for(let p=0,n=2;a[e]==f;n+=c)if(b.x+=l*n,b.y+=h*n,b.w+=m*n,b.h+=q*n,yield t(b),++p<k)yield _za(r);else{b.includes(d)||(g=_2i(_D(d)),yield t(d));break}}})}function _2i(a){return((_Zw[a]||{}).dpiX||96)/96}function _8j(a){return _2i(_wt(a))}function _3s(a,b){const d=_8j(a);return 1==d?_df(a).includes(b):Math.max(Math.abs(b.x-a.left*d),Math.abs(b.y-a.top*d),Math.abs(b.w-a.width*d),Math.abs(b.h-a.height*d))<=Math.max(2,10/Math.pow(d,2))}
function _wt(a){a.monitorId||(a.monitorId=_D(_df(a)));return a.monitorId}function _D(a){let b=-Infinity,d=0;for(let c in _Zw){let e=_ie(_Aj(a,_df(_Zw[c].bounds)));e>b&&(b=e,d=c)}return d}function _Ao(a,b){let d=Math.max(1,Math.round(a.w/b.w))*b.w,c=Math.max(1,Math.round(a.h/b.h))*b.h;return{x:b.x+b.w*Math.round((a.x-b.x+a.w/2-d/2)/b.w),y:b.y+b.h*Math.round((a.y-b.y+a.h/2-c/2)/b.h),w:d,h:c}}
function _gf(a,b){b in _Zw||(b=Object.keys(_Zw)[0]);let d=_Zw[b].workArea;a=_ls(a,b);return{x:d.left,y:d.top,w:Math.round(d.width/a.cols),h:Math.round(d.height/a.rows)}}function _8y(a){let b=0;for(let d in _Zw){let c=_ie(_Aj(a,_df(_Zw[d].workArea)));0<c&&(b+=c)}return b}function _3w(a,b,d){let c="x"==d?"w":"h";return(Math.min(a[d]+a[c],b[d]+b[c])-Math.max(a[d],b[d]))/Math.min(a[c],b[c])}
function _i(a,b,d,c){var e=b[c]-a[c];e/=Math.abs(e);for(a={}.add(a);;){let f=_8y(a)/_ie(a),g=_3w(d,a,c);if(.99<f||.99<g)break;a[c]+=e*b["x"==c?"w":"h"]}return a}function _2r(a,b,d){a={}.add(a);let c={}.add(a),e=0,f=!1;for(;;){let g=_8y(c)/_ie(c);if(.99<g){a.add(c);break}if(g>e)a.add(c),e=g;else if(f)break;else f=!0,c.add(a);c[d]-=b[d];f&&(c["w"==d?"x":"y"]+=b[d])}return a}
function _Xe(a,b,d,c){let e=_D(a),f=_gf(b,e);d=d?_gf(b,d):f;a=_Ao(a,f);let g=a.sc();for(let h of["x","y","w","h"]){let m=c[h]||{};if("val"in m){let q=+m.abs?"x"==h?d.x:"y"==h?d.y:0:a[h];var l=+m.abs?d:f;l=h.in("x","w")?l.w:l.h;a[h]=q+m.val*l;h.in("w","h")&&0>=a[h]&&(a[h]=l)}}a.includes(g)||(e=_D(a),f=_gf(b,e),a=_Ao(a,f));if(!_Zw[e])return _Ot("badMonitorId",{monId:e,rect:a,MONITORS:_Zw}),a;b=_df(_Zw[e].workArea);a=_i(a,f,b,"x");a=_i(a,f,b,"y");a=_2r(a,f,"w");return a=_2r(a,f,"h")}
function _Mr(a,b){return _ji(_Zw,a||_D(b),"workArea")||{left:0,top:0}}function _ey(a,b,d){a=a.sc();b=_Mr(b,a);for(let c of["x","y","w","h"]){let e=d[c]||{};if("val"in e){let f="x"==c?b.left:"y"==c?b.top:0;a[c]=(+e.abs?f:a[c])+e.val;"w"==c&&(a[c]=Math.max(100,a[c]));"h"==c&&(a[c]=Math.max(25,a[c]))}}return a}
function _Xr(a,b,d){a=a.sc();b=_Mr(b,a);for(let c of["x","y","w","h"]){let e=d[c]||{};if("val"in e){let f="x"==c?b.left:"y"==c?b.top:0,g=a[c.in("x","w")?"w":"h"];a[c]=(+e.abs?f:a[c])+g*e.val/100;"w"==c&&(a[c]=Math.max(100,a[c]));"h"==c&&(a[c]=Math.max(25,a[c]))}}return a}
function _ws(a){let b=_gh(a.gridLayout,"gridLayout").value,d=_ls(b,a.baseMonitor),c=+a.cols||+d.cols,e=+a.rows||+d.rows;return[function*(){let f=0,g=0;for(;;)yield _Xe({x:1,y:1,w:1,h:1},b,a.baseMonitor,{x:{abs:1,val:(a.x||0)+f},y:{abs:1,val:(a.y||0)+g},w:{abs:1,val:1},h:{abs:1,val:1}}),++f==c&&(f=0,++g==e&&(g=0))}(),c*e]}_Du.gridLayout={grid2x2:{name:"2 x 2 grid",value:{"*":{cols:2,rows:2}}},grid2x1:{name:"2 x 1 grid",value:{"*":{cols:2,rows:1}}},grid3x1:{name:"3 x 1 grid",value:{"*":{cols:3,rows:1}}}};
let _O=_we(function*(a){a=yield _Vy(_6f,yield _1h(a));let b={};for(let [d,c]of a)b[_Or[d]]=c;return b});
