'use strict';{let v=new _Wf,z;var _4=_cg(function*(){_8a(_Du.menuStyle);_8a(_if.menuStyle);_Lk(_wr,[yield _Zs(yield _Fh("/res/swtchOff.svg",16,16)),yield _Zs(yield _Fh("/res/swtchOn.svg",16,16))]);_ij(yield _Fh("/res/actionIcon.svg",16,16),a=>z=a);v&&v.send()});try{_4()}catch(e){try{console.warn("[AC-MV3] file26 init deferred (no DOM yet):",e&&e.message)}catch(_){}}var _Tu=function(a,b=_Ck.items){return b&&b[a]};let A=_we(function*(a,b,e){let d=_Ck.items,h=d.length,k=[];var g=0;let l=b.commonOptions||{};const n=l.withPreviews?_Fi:l.thumbSize;var f=l.sc().del("maxItems"),m=b.sc().keep("break","sepLine");
const q=f.noTitles;if(b.type.in("TSE","tabGroups")){let c="TSE"==b.type?yield _ai(e,_gt,b.content):b.content;for(let p of c){const r=!g++;k.push({noTitle:q,title:p.length+" tabs",icon:"res/tabs.png",subMenu:!0,itemType:_gk}.add(r?m:null));d.push({type:"tabList",content:p,commonOptions:f}.add(r?m:null))}1==c.length&&(b=d.pop(),k=[],g=0)}if("tabList"==b.type)for(let c of b.content)f={noTitle:q,title:_Yp[c].title,icon:_ig(_zh(_Yp[c])),itemType:_ju},0==g++&&f.add(m),n&&f.add({previewId:c,thumbSize:n}),
k.push(f),d.push({type:"tab",content:c});else if(b.type.in("closedTabs","closedWin")){a="closedWin"==b.type?b.content.tabs:_Yk.sessions?(yield c=>_Yk.sessions.getRecentlyClosed(c)).map(c=>c.tab||c.window):[];for(let c of a)a={noTitle:q,title:c.tabs?c.tabs.length+" tabs":c.title,icon:c.tabs?"res/tabs.png":_ig(c.url),subMenu:c.tabs?!0:void 0,itemType:c.tabs?_Pg:_et},0==g++&&a.add(m),n&&!c.tabs&&a.add({previewId:+c.sessionId,thumbSize:n}),k.push(a),d.push({type:c.tabs?"closedWin":"closedTab",content:c,
commonOptions:c.tabs?f:void 0})}else if(b.type.in("bmFolder","bmSubFldr")){a=_Yk.bookmarks&&(yield c=>_Yk.bookmarks.getChildren(b.content+"",c))||[];for(let c of a)k.push({noTitle:q,title:c.title,icon:c.url?_ig(c.url):"res/folder.png",subMenu:!c.url,itemType:c.url?_Nu:_yr}.add(g++?null:m)),d.push({type:c.url?"bookmark":"bmSubFldr",content:c.id,commonOptions:c.url?void 0:f})}else if("custom"==b.type){g=new x;for(let c of b.content)if(g=g.addNeighbor(1),c.subMenu||c.type.in("custom","action","switch")){let p,
r,w,t;if("TSE"==c.type)p=_gh(c.content,"tse").name||"(Unnamed tab selection)",r="res/tabs.png",w=!0,t=y(c.type);else if("closedTabs"==c.type)p=c.title||"Closed tabs",r="res/tabs.png",w=!0,t=y(c.type);else if("custom"==c.type)p=c.title||"(Unnamed submenu)",w=!0;else if("bmFolder"==c.type){if(m=(_Yk.bookmarks&&(yield E=>_Yk.bookmarks.get(c.content+"",E))||[])[0])p=m.title,r="res/folder.png",w=!0,t=y(c.type)}else if("action"==c.type)(m=yield _ru("trigActList",c.content))&&!m.disabled&&(p=m.title||"(Unnamed action)",
r=m.icon&&m.icon.img||z,t=_Te);else if("switch"==c.type&&c.content){p=_gh(c.content).name;t=_Ju;var F=+_wh(c.content)[1]}p&&(k.push({noTitle:q,title:p,icon:r,itemType:t,switchId:F,subMenu:w,break:c.break,sepLine:c.sepLine}),m={commonOptions:f.sc().add(c.commonOptions)}.add(c.sc().del("commonOptions","break","sepLine"),{parentID:a,itemIdx:g}),d.push(m))}else m={commonOptions:f.sc().add(c.commonOptions)}.add(c.sc().del("commonOptions")),m=yield A(a,m,e),k.push(...m)}l.maxItems&&(d.splice(h+l.maxItems),
k.splice(l.maxItems));return k}),y=a=>({TSE:_gk|_gd,bmFolder:_yr|_gd,closedTabs:_6o})[a]||_le,B=_we(function*(a,b,e){a=yield A(a,b,e);b=b.commonOptions||{};var d=a.length,h=b.itemsDistrib&&b.itemsDistrib[0]?b.itemsDistrib:b.layout!=_Ah("R")?["numGroups"]:["auto"];d="auto"==h[0]?Math.ceil(Math.sqrt(d)):"numGroups"==h[0]?Math.ceil(d/(h[1]||1)):h[1]||1;let k=new _wk;h=0;let g=!0;for(let l of a)l.break&&(h=0),l.break=0!=h||g?void 0:!0,l.icon&&_Zs(l.icon)(k.onReady(n=>l.icon=n)),g=!1,h=++h%d;yield l=>
k.setCallback(l);_Ck.trigInstId=e;return{style:"std",items:a}.add(b)}),G=(a,b)=>{try{B(a,_Ck.items[a],_Ck.trigInstId)(e=>_ha(b,e))}catch(e){_Ot("menuError",{stack:e.stack}),_ha(b,[])}},C=(a,b,e)=>a==b?e:a==e?b:a;var _Bp=_we(function*(a,b,e,d=!1){v&&(yield v.wait(),v=void 0);if(!_Ck.items||(yield H())){_Ck={items:[null],busy:!0};var h=b.rootOptions||{},k=h.position||"mouse";if(yield _Vy(_b,{menuData:yield B(a,b,e),menuEntityNum:_lk(a),position:_Ah(k[0].toUpperCase()),alignHorz:"mouse"==k?C(h.alignHorz,
_Nr,_Dp):h.alignHorz,alignVert:"mouse"==k?C(h.alignVert,_ug,_2g):h.alignVert,menuSystem:h.menuSystem,usePrvMsPos:d}))_Ck.id=a;delete _Ck.busy}});let u,H=()=>(a=_ay)=>{u=b=>{u=null;a(b)};_Lk(_Ws,null,b=>{b||u&&u(!1)})||_Uj(_Wr)},I=a=>{a&&(_Zk={[_Ck.id]:Date.now()});_Ck.busy||(_Ck={});u&&u(!0)};{const a=[{action:"alterTgtTabs",params:{tse:[{oper:"slice",params:{from:1,to:1}}]}},{action:"activateTabs"}],b=(e,d)=>[{sequence:[{action:"loadUrls",params:{bookmarkId:e}.add(d?{tabPos:"after",refTab:"lastTab"}:
null)}].concat(2==d?a:[]),targets:"currentTab"}];var _9o=_we(function*(e,d=0){const h=_Ck.items;let k=_Tu(e,h);if(k){yield _Rf();const g=k.type,l=k.content;let n;if("action"==g)2!=d&&(n=yield _rf(_ek[l]||[],null,_qt(null,{usePrevMousePos:!0})));else if("switch"==g)2!=d&&_2t(l,-1);else if("bookmark"==g)e=b(l,d),n=yield _rf(e);else if("bmFolder"==g||"bmSubFldr"==g)0!=d&&(n=yield _rf(b(l,d)));else if("TSE"==g||"tabList"==g){if(2==d){let f="TSE"==g?yield _ai(h.trigInstId,_gt,l):_Dw(l);yield m=>_Zj(f,
m);_Lk(_vy,e)}}else"tab"==g?2==d?(yield f=>_Zj(_Dw(l),f),_Lk(_vy,e)):(n=yield f=>_Ph(_Dw(l),f),yield f=>_Ny(n,f)):"closedTabs"!=g&&("closedWin"==g?0!=d&&(d=yield f=>_Yk.sessions.restore(l.sessionId,f),n=(_ji(d,"window","tabs")||[]).map(f=>f.id),_Lk(_vy,e)):"closedTab"==g&&2!=d&&(d=yield f=>_Yk.sessions.restore(l.sessionId,f),(d=_ji(d,"tab","id"))&&(n=[d]),_Lk(_vy,e)));_Fk=!0;return n}})}let J=_we(function*(a){let b=_Tu(a,_Ck.items);if(b)switch(b.type){case "bookmark":return _ji(yield e=>_Yk.bookmarks.get(b.content+
"",e),0,"url");case "tab":return _zh(_Yp[b.content]);case "closedTab":return b.content.url}}),D=(a,b)=>{let e=[];for(;a;){e.unshift("content",a.itemIdx);if("string"==typeof a.parentID){e.unshift(a.parentID);break}a=_Tu(a.parentID,b)}return e},K=_we(function*(a,b,e,d){var h=_Ck.items;let k=_Tu(a,h),g=4294967294==b?{parentID:e,itemIdx:new x}:_Tu(b,h);if(k&&g){if(k.type.in("bookmark","bmSubFldr")){if(4294967294==b)var l={parentId:_Tu(e,h).content};else(b=_ji(yield f=>_Yk.bookmarks.get(g.content,f),0))&&
(l={parentId:b.parentId,index:b.index+("B"==d?1:0)});return l&&(yield f=>_Yk.bookmarks.move(k.content,l,f))}e=D(k,h);var n=D(g,h);h=e[0];if(_hf(h)&&!n.join(" ").startsWith(e.join(" "))){a=_gh(h).value;e=_ji(a,...e.slice(1,-1));n=_ji(a,...n.slice(1,-1));let f=e[k.itemIdx],m=n[g.itemIdx],q=e[k.itemIdx+1];q&&(f.sepLine&&(q.sepLine=!0),f.break&&(q.break=!0));f.del("sepLine","break");4294967294==b&&(d="B");"T"==d&&(m.sepLine&&(f.sepLine=!0),m.break&&(f.break=!0),m.del("sepLine","break"));d="B"==d?1:0;
e.remove(f);n.splice(n.indexOf(m)+d,0,f);k.parentID=g.parentID;k.itemIdx.remove();k.itemIdx=g.itemIdx.addNeighbor(d);_1e([h,"value"],a,0);return!0}}}),x=function(a,b){this.list=a?a.list:[];null!=b&&this.list.splice(a+b,0,this)};x.prototype={valueOf(){return this.list.indexOf(this)},toString(){return+this},addNeighbor(a){return new x(this,a)},remove(){this.list.splice(+this,1)[0].list=null}};let L=(a,b)=>[];_cu({[_ra]:a=>G(a.itemId,a.callback),[_7a]:a=>J(a.itemId)(b=>_ha(a.callback,b)),[_ni]:a=>K(a.srcItmId,
a.tgtItmId,a.tgtParentId,_Lj(a.insertPos))(b=>_ha(a.callback,!!b)),[_rp]:a=>_9o(a.itemId,a.selMode)(),[_9u]:a=>_ha(a.callback,L(a.itemId,a.parentId)),[_Wr]:a=>I(a&&a.click)})};
