'use strict';let _rk=0;function _mw(){return _rk||"undefined"!=typeof _Vj&&!_ul(_Vj)}function _To(b,f,g,l){let m=g.bkgrnd?[0]:_qd(b);++_rk;_gr(g.scriptId,m,b,l)(e=>{--_rk;g.async||f(e)});g.async&&f(b)}
let _gr=_we(function*(b,f,g,l){let m=yield _zs(b);if(m){b=yield _Ue(b,f,g,m,void 0,l,!0);f=!1;l=[];for(let e of b)if(e)if(e===(e|0)&&(e=[e]),_Jw(e))f=!0,l.push(...e.map(n=>_Jw(n)?_Dw(n):_Yp[n]?n:null).filter(n=>n));else if("object"==typeof e&&"string"==typeof e.break&&1==Object.keys(e).length)return e;if(f)return l}return g}),_Ue=_we(function*(b,f,g,l,m,e,n,r){let a=[];for(let c of f)0<=c&&a.push(_A(b,c,g,l,m,e,n,r));return yield Promise.all(a)}),_Yh;
{var _A=function(a,c,d,h,p,k,t,u){return new Promise((v,w)=>{_xj(c,{scriptId:a,tabId:c,targetTabs:d,funcCode:p?h+"":`${55>_rs?"":"async"}()=>{\n${h}\n}`,args:_Ii(p),/* AC-MV3 FIX (2026-08-05, FEATURES-MV3.md §7-13): append a per-MESSAGE ~suffix to the
      trigInstId. The nested runInTab/runInFrames execUserFunc carried the
      PARENT's raw trigInstId → the SW dedup saw the parent's key as still
      in-flight → BLOCKED every nested call → runInTab returned [null].
      The suffix is IN THE MESSAGE: the n() retry re-sends the SAME message
      (same suffix → retry-dup still dedup'd), while each nested call gets
      its own key ≠ the parent's (no false block). Deterministic per message,
      like the round-6 ~suffix in file42. */trigInstId:(k||"")+"~"+(Math.random()+"").slice(2),/* AC-MV3 FIX (2026-08-06, round 7b): noWait marks the TOP-LEVEL RUN SCRIPT (t===true from _To/_gr). The scriptId branch acks it immediately (fire-and-forget, result unused) but MUST await nested _A calls (runInTab/runInFrames — noWait falsy) and return their REAL result — round-7 made them return [true]. */noWait:!0===t,frmFlt:u})(q=>{q=q||{};!t&&"error"in q?w(q.error):v(q.result)})})},_xj=(a,c)=>(d=_ay)=>{+a?c.frmFlt?r(+a,c,d):n(+a,c,d):e(c,d)};window.addEventListener("message",a=>m(a.data,{id:0},c=>a.source.postMessage({result:c,pongId:a.data.pingId},"*")));
// FIX: Don't block SW broadcast messages (they have _sw flag)
// Only return true (async) when we actually handle the message
_Yk.runtime.onMessage.addListener((a,c,d)=>{if(a._sw)return false; // Skip SW broadcasts
m(a,c.tab,d);return!0});
let b={},f=
a=>{for(var c=1;c in b;++c);b[c]=a;return c};const g=a=>_Yk.runtime.getURL(_ak)+"?file="+encodeURIComponent(a),l=_Es(-700,a=>_0j()(c=>_Xp(c)._ja(a)));let m=function(a,c,d){if(a.pongId)b[a.pongId]&&"dontDel"!=b[a.pongId](a.result)&&delete b[a.pongId];else if(c&&"userAPI"==a.type){++_rk;let h=()=>_Yh(a,c)((...p)=>{--_rk;d(...p)});_Yh?h():_9w("/file77.js",h)}else a.imprtSttgs?(window._ja||l)(a.imprtSttgs):a.viewSttgs?_Yk.tabs.create({active:!0,url:g(a.viewSttgs)}):a.redirSttgs&&_Yk.tabs.update(c.id,{url:g(a.redirSttgs)})},
e=_cg(function*(a,c){let d=document.getElementById("BGScript");d||(d=_Uu('<iframe id=BGScript src="file23.html">').children[0],yield h=>{d.onload=h;document.body.appendChild(d)});a.pingId=f(c);d.contentWindow.postMessage(a,"*")}),n=_cg(function*(a,c,d){const t0=performance.now();let rs="";for(let p=0;;++p){var h=yield k=>{let once=!1;const fin1=(x,why)=>{if(once)return;once=!0;rs=why||("undefined"===typeof x?"cb-undef":x?"cb-val":"cb-null");k(x)};try{_Yk.tabs.sendMessage(a,c,{frameId:0},x=>fin1(x,(_Yk.runtime.lastError?"lasterr:"+_Yk.runtime.lastError.message:"cb-ok")))}catch(e){fin1(void 0,"throw:"+String(e&&e.message||e))}/* AC-MV3 FIX (2026-08-06, round 14): 8000 → 6000ms. The FIRST
   userScripts.execute on a fresh page costs ~4-5s one-time (Chrome inits
   its userScripts subsystem; user VM 19:27: first execUserFunc +4909ms).
   round 13 raised the timeout 4000 → 8000ms so legit first calls could
   wait out the init without a retry/double-exec — but the KNOWN FEATURES-MV3.md §7-6 gap
   (runInPageCtx(func)) NEVER returns its result, so the test waited the
   FULL timeout: user VM 19:40 FAIL +8031ms (was +4031-4038ms with 4000ms).
   6000ms is the compromise: legit first calls (init ~4-5s) still fit, the
   gap FAILs in ~6s instead of 8s. The document-guard in file42.js makes
   the re-injection fallback a no-op anyway; the retry still re-sends the
   SAME message (SW dedup + __acFnDedup make it harmless).
   */setTimeout(()=>fin1(void 0,"timeout"),6000)};_Aw("msgToIsolCtx");/* AC-MV3 FIX (2026-08-06, round 6): treat null like undefined — retry. A STALE file42 instance (pre-guard, survives until the tab reloads) can win the sendMessage channel race with sendResponse(null) → F() destructures null → "_fr is not iterable" (VM 14:30 logs: setClipboard F-> null while the fresh instance logged the correct funcCode val). One retry re-sends the SAME message; with the round-6 K fix (non-destructive read) and the value-promise dedup, EVERY instance answers the SAME correct value → the retry converges. */if(null!=h||0<p||c.event){0<a&&console.warn('[AC-DLV] tab='+a+' resp +'+(performance.now()-t0).toFixed(0)+'ms attempt='+(p+1));break}try{0<a&&console.warn('[AC-DLV] tab='+a+' no listener → inject file42 attempt='+(p+1));yield _wj(a,{file:"file42.js"})}catch(k){return d({error:k})}}/* AC-MV3 DIAG (2026-08-06): what exactly did n() receive from the tab? F()-path (setClipboard/runInPageCtx file) failures show funcCode val logged but the SW destructure getting a non-iterable — this shows the raw sendMessage response. */0<a&&console.warn('[AC-DLV-F] tab='+a+' trig='+String(c&&c.trigInstId).slice(0,70)+' why='+rs+' h='+(void 0===h?'UNDEF':Array.isArray(h)?'ARR['+h.length+']':typeof h+':'+String(h&&h.message||h).slice(0,120)));d(h)}),r=_cg(function*(a,c,d){try{let h=
yield _wj(a,{allFrames:!0,matchAboutBlank:!0,code:"!!window.FN"});h.filter(k=>!k).length&&(h=yield _wj(a,{allFrames:!0,matchAboutBlank:!0,file:"file42.js"}));let p=h.length;h=[];c.frmCBId=f(k=>{if(k){if("error"in k)return d(k);h.push(k.result)}if(--p)return"dontDel";d({result:h})});yield k=>_Yk.tabs.sendMessage(a,c,k);_Aw()}catch(h){return d({error:h})}})}let _zs=_we(function*(b){(b=_gh(b,"script").value)&&b.srcFile&&(b=yield _L(b.srcFile,!0));return b?b.srcCode:""});
var _L=_we(function*(b,f){b=yield _sp(b);let g=_lo(b);if(_1(b)||!_Nf(b)){f=yield _If(b,"text",_ji(g,"ldTime")||0);if(f.error)return{error:f.error};if(null!=f.content)return _lo(b,{srcCode:f.content,encode:f.charEnc,ldTime:Date.now()})}else if(!g||6E4<Date.now()-g.checkTime){let l=_we(function*(){let [m,e]=yield _mg(_1p(b,"text",void 0,void 0,{"If-Modified-Since":(new Date(_ji(g,"ldTime")||0)).toUTCString()}));return 200==e.status?_lo(b,{srcCode:m,ldTime:Date.now(),checkTime:Date.now()}):304==e.status?
_lo(b,g.add({checkTime:Date.now()})):{error:e.status}});if(f&&g)l()();else return yield l()}return g});
_Du.script={saveAllImg:{name:"Example 1: Download all images",help:"",value:{srcCode:"let count = 0 ;\n//for each image in the page\nfor(let image of document.images){\n\t//if the image is bigger than 100x100 pixels\n\tif( image.src && image.width > 100 && image.height > 100 ){\n\t\t//save it to the desktop under a folder named after the page's domain\n\t\tlet filepath = await ACtl.saveURL(image.src, `<desktop>/${location.hostname}/`) ;\n\t\tconsole.log(++count, image.src, ' --\x3e ', filepath) ;\n\t}\n}\nalert(count + ' IMAGES SAVED.') ;"}},captTabPub:{name:"Example 2: Take page screenshot and upload it",
help:"",value:{srcCode:"//Take a shot of the current tab\nlet [[, dataUri]] = await ACtl.captureTab('#currentTab') ;\n//Put the image in the clipboard\nawait ACtl.setClipboard({image: dataUri}) ;\n//Open https://snipboard.io in a new tab\nlet [tabId] = await ACtl.openURL('https://snipboard.io', {rightOf: '#currentTab'}) ;\n//Wait for the tab to finish loading\nawait ACtl.on('tabLoadEnd', tabId) ;\n//Activate the new tab and focus its window\nawait ACtl.setTabState(tabId, 'active focused') ;\n//Execute AutoControl's [CLIPBRD PASTE] action\nawait ACtl.execAction('#clpbrdPaste') ;"}}};
