'use strict';let _Up={tse:{editor:_ry(),newName:"My custom tab selection",newValue:[],genericName:"tab selection"},gridLayout:{editor:_P,newName:"My grid",newValue:{},genericName:"grid layout"},menuSpec:{editor:_oy(),newName:"My custom menu",newValue:{type:"custom",content:[]},genericName:"menu"},menuStyle:{editor:_ay,newName:"My menu style",newValue:{},genericName:"menu style"},binSwtch:{editor:_ay,newName:"My switch",newValue:{},genericName:"switch"},script:{genericName:"script"}};const _wg="Other...";
let _3y={1:"Favorite list One",2:"Favorite list Duo",3:"Favorite list Terna",4:"Favorite list Quater",5:"Favorite list Penta",6:"Favorite list Hex",7:"Favorite list 7",8:"Favorite list Octave",9:"Favorite list Nona",10:"Favorite list X"};function _Kr(a){let b=0;for(;++b in(_9j._if[a]||{}););return a+":"+b}function _Mp(a,b){return(c=_ay)=>{let e=_Kr(a),d={name:"binSwtch"==a?`${_Up[a].newName} ${Object.keys(_9j._if[a]||[]).length+1}`:"",value:b||_ty(_Up[a].newValue)};_1e(e,d,0,()=>c(e))}}
function _Bd(a,b){_vw(a,c=>{c?_u(`This item is being used in <r>${c}</r> other places. <br> It cannot be deleted.`):_8i(a,b)})}function _8i(a,b){let c=_wh(a)[0];if("script"==c){let e=_ji(_gh(a),"value","srcFile");e&&_9j._sp(e)(d=>{_lo(d,void 0)});_aa(a)()}_1e(a,void 0,0,()=>{"menuSpec"==c&&_Yr(0);b&&b()})}
function _lp(a){_9i({trigActList:null,customEntities:{},mouseGest:{}},b=>{for(let [e,d]of b.customEntities.tse||{})b.customEntities.tse[e]=JSON.stringify(d);const c=JSON.stringify([b.trigActList,b.customEntities.menuSpec,b.mouseGest.triggers]);a(e=>{let d=0,f=new RegExp('"'+e+'"',"g"),[g,h]=_wh(e);if("tse"==g)for(let [k,l]of b.customEntities.tse||{})h!=k&&(d+=(l.match(f)||[]).length);return d+(c.match(f)||[]).length})})}function _vw(a,b){_lp(c=>b(c(a)))}
let _Ud=(...a)=>_me(a,!0),_me=_we(function*(a=[],b){do{var c=!1;let e=yield f=>_lp(f),d=new _wk;a.length||(a=Object.keys(_9j._if));for(let f of a)for(let [g,h]of _9j._if[f]||[])if(!b||!h.name||!h.value||"binSwtch"==f){const k=f+":"+g;0==e(k)&&(_8i(k,d.onReady()),!c&&f.in("tse","menuSpec")&&(c=!0))}yield f=>d.setCallback(f)}while(c)});function _z(a){return!!$(a).find("[entityType=binSwtch][value^=b]")[0]}function _Yr(a=0){setTimeout(()=>_Ud("binSwtch")(),a)}
function _Au(a=0){setTimeout(()=>_Ud("menuSpec")(),a)}let _mf=_we(function*(a,b){var c=_wh(a)[0];let e=_Up[c].genericName;if(b)for(let d of _Xy(c)){if(c=_gh(d).name,d!=a&&!_Vo(b,c))return _u(`There's already a ${e} called <b>${c}</b>. <br> Please enter a different name.`,{type:"warning"}),[!1]}else if((b=_gh(a).name)&&1<(yield d=>_vw(a,d)))return _u(`This ${e} is being used in more than one place. <br> Its name cannot be blank.`,{type:"warning"}),[!1,b];return[!0]});
function _Ri(a){var b=_wh(a)[0];let c=_ty(_gh(a,b)),e=_Up[b].genericName,d=$(`\n <namedEntityEditor DataModule>\n <div>\n <input type=text spellcheck=false maxlength=80 placeholder="Give a name to this ${e} (optional)" title="Click to change name">\n <h h=/entName ent="${e}"></h>\n </div>\n </namedEntityEditor>\n `).prop("value",c.value).on("change",function(){_1e([a,"value"],this.value,100,()=>{$(`[value='${a}']`).triggerEvt("redefine",!0)})}).on("close",function(){$(this.children).triggerEvt("close")}).find("input").val(c.name).on("input",
_Es(250,_cg(function*(){let f=this.value.trim(),[g,h]=yield _mf(a,f);h&&(this.value=h);if(!g)return!1;_1e([a,"name"],f);$(`[value='${a}'] > l`).text(f||_wg);$(this).closest("floatbox").triggerEvt("resize")}))).change(!1).end();d.updateEmptyState=function(){this.toggleClass("empty",$("> .empty",this)[0])};b=_Up[b].editor(d[0]).on("change",()=>d.updateEmptyState());d.append(b).prop("onInitDone",b[0].onInitDone).updateEmptyState();return d}
function _br(a,b){return _3p(a,b,"brlt RR,HR","tailAndShadowBlurry","auto-detect","transformAndOpacitySlow")}function _jw(a,b){return _ue("binSwtch",a,b,"",!1,!0,!1,"",!1)}
function _ue(a,b,c,e,d=!1,f=!0,g=!0,h="",k=!0){let l=_gh(c,a);e=e||`Choose a ${_Up[a].genericName}...`;d&&"boolean"==typeof d&&(d="(blank)");return`<customSelect entityType=${a} name="${b}" value="${c||""}" ${f?"newOpt":""} ${d?`emptyOpt="${d}"`:""} ${g?"editBtn":""} ${k?"":"noDelBtn"} optionsFilter="${h}" placeholder="${e}">${_hf(c)?`<l>${l.name||_wg}</l>`+(g?" <edit></edit>":""):l.name||""}</customSelect>`}
function _7t(a,b,c){let e=b instanceof HTMLElement,d=e?$(b).attr("value"):b,f="binSwtch"==$(a).attr("entityType");c=(f?"":c)||(e?$("l",b).text()||$(b).text():_gh(d,$(a).attr("entityType")).name||"");let g=$(a).attr("value");if(_hf(g)){let h=_gh(g);h.name&&!f||_vw(g,k=>{1>=k?(_8i(g),a.prevAnonEntity=h.value):f||(a.prevAnonEntity=g)})}$(a).attr("value",d).html(_hf(d)?`<l>${c}</l>`+($(a).is("[editBtn]")?"<edit></edit>":""):`${c}`).triggerEvt("change",!0)}
function _gy(a,b,c,e){let d=_gh(b,a),f=_hf(b);return`<item value="${b}" ${f?"custom":""} ${d.perms?`perms="${d.perms}"`:""} ${b==c?"selected":""}>\n <l>${d.name}</l> ${d.help?`<h h="/${a}/${d.help}"></h>`:""} ${f&&!e?'<del button title="Delete"></del>':""}\n </item>`}
function _Rt(a){var b=$(a).attr("value");let c=$(a).attr("entityType"),e=$(a).attr("emptyOpt"),d=$(a).attr("optionsFilter"),f=$(a).is("[newOpt]"),g=$(a).is("[noDelBtn]"),h="",k="";for(let [l,m]of _9j._Du[c])if(!d||d in m)h+=_gy(c,l,b,g);for(let l of _Xy(c,!0))k+=_gy(c,l,b,g);b=$(`\n <namedEntityMenu DataModule>\n ${e?`<item value="" label="${e}"></item>`:""}\n ${h}\n ${h&&k?"<hr>":""}\n ${k}\n ${f?`\n <hr>\n <newEntity type=${c}>New ${_Up[c].genericName}...</newEntity>\n `:""}\n </namedEntityMenu>\n `);
return _ii(b,a)}function _Ss(...a){return _ue(...a)}
function _ii(a,b){return $(a).on("click","item",function(){$(this).triggerEvt("focusLost",!0);_7t(b,this)}).on("click","newEntity",_cg(function*(){var c=$(b).attr("value");if(!_hf(c)||_gh(c).name)c=b.prevAnonEntity,c="string"==typeof c?c:yield _Mp($(this).attr("type"),c),_7t(b,c,_wg);$(this).triggerEvt("focusLost",!0);setTimeout(()=>$("edit",b).triggerEvt("mousedown"),200)})).on("click","del",function(c){c.stopImmediatePropagation()}).on("dblclick","del",function(c){c=$(this).closest("item").attr("value");
_Bd(c,()=>$(this).closest("item").remove())})}function _Gg(a,b){let c={};for(let e of a)a=_gh(e,b),c[e]=[a.name,a.help?"/"+b+"/"+a.help:""];return c};
