'use strict';function _9i(a,b,k=_Yk){k.storage.local.get(a,g=>{setTimeout(()=>b(_Qj(g||_ty(a)||{})))})}function _bd(a,b){_Yk.storage.local.set(_bj(a),()=>{b&&setTimeout(b)})}function _bj(a){a=a.sc();"trigActList"in a&&(a.trigActList=a.trigActList.toJSON());if("customEntities"in a){a.customEntities=a.customEntities.sc();for(let b in a.customEntities)a.customEntities[b]=[...a.customEntities[b]]}return a}
function _Qj(a){"trigActList"in a&&(a.trigActList=_la(a.trigActList));if("customEntities"in a)for(let b in a.customEntities)a.customEntities[b]={}.add(a.customEntities[b]);return a}function _Mw(a,b,k){a=a.sc().del(Object.keys(b));_ul(a)?k(b):_9i(a,g=>k(g.add(b)))}let _ru=(...a)=>b=>{_9i({[a[0]]:null},k=>b(_ji(k,...a)))};
{let a={},b=Symbol(),k=Symbol();var _Gu=function(...l){let r=l.pop();for(let n of l)"string"==typeof n&&(n=n.split(".")),l=""===n.slice(-1)[0]?(n.pop(),b):k,_lf(a,...n,l,[]).add(r)},_9y=function(...l){l[l.length-1].runOnce=!0;return _Gu(...l)},_B=function(...l){l[l.length-1].grpChng=-1;return _Gu(...l)};let g=function(l){function r(t,p,w){if(t){t[k]&&n.push({funcs:t[k],path:p});t[b]&&0==w.length&&n.push({funcs:t[b],path:p});p=p.concat(w.slice(0,1));let c=w.slice(1);r(t["*"],p,c);r(t[w[0]],p,c)}}let n=
[];r(a,[],l);return n},m,v=[],x=0;var _Mi=function(l,r,n=300,t){clearTimeout(m);v.push({keyPath:_Ii(l),value:r,callback:t});m=setTimeout(()=>{let p=v;v=[];let w={};for(let c of p)w[c.keyPath[0]]=null;++x;_9i(w,c=>{for(let e of p)_lf(c,...e.keyPath,e.value,NaN);_bd(c,()=>{const e=_Aw();let d={};for(let h of p){if(!e){var f=g(h.keyPath);for(let q of f){f=q.funcs;const y=_lf(d,q.path.join(),[]);for(let z=f.length;z--;){const u=f[z];u.grpChng?u.grpChng!=x&&(u.grpChng=x,u(c,q.path)):u.runOnce?(f.splice(z,
1),u(c,q.path)):0>y.indexOf(u)&&(y.push(u),u(c,q.path))}}}h.callback&&setTimeout(()=>h.callback(e))}})})},n)}}
let _sy=(a,b=0)=>(k=_ay)=>{let g=new _wk;for(let [m,v]of a)_Mi(m.split("."),v,b,g.onReady());g.setCallback((...m)=>{m=m.filter(v=>v)[0];k(m)})},_Ad=()=>a=>_Yk.storage.local.get(null,b=>a(b.del("LOCAL"))),_Sp=_we(function*(a){var b=window==_9j;if(b||(yield _Qk(_xk(a),"permMsgs/newSttgs"))){var k=yield g=>_9i({LOCAL:{}},g);
// AC-MV3: never lose entities that are missing from the imported file (e.g.
// scripts created after the last file write). Merge old customEntities in.
var _old=(yield g=>_9i({customEntities:{}},g)).customEntities;
try{console.warn("[AC-MV3] _Sp import from file: hasScript="+!!(a&&a.customEntities&&a.customEntities.script)+" oldScripts="+((_old&&_old.script)?Object.keys(_old.script).length:0)+" oldTypes="+(_old?Object.keys(_old).join(","):"-"))}catch(e){}
if(a&&a.customEntities&&_old)for(var _t in _old)if(_old[_t]&&!(String(_t) in a.customEntities)){try{a.customEntities[String(_t)]=JSON.parse(JSON.stringify(_old[_t]))}catch(e){}}
yield g=>_Yk.storage.local.clear(g);yield g=>_Yk.storage.local.set(a.add(k),g);if(_Aw())b||_u("ERROR: \n\n"+_Aw(),{type:"error"});else{yield g=>_9j._ku(g);if(b){(yield g=>_3d(a,g))||
_Yk.permissions.remove({permissions:["background"]});b=yield _zg({url:_Yk.runtime.getURL(_ak)});for(let g of b)_Yk.tabs.reload(g.id)}else _Rg("New settings imported successfully. <hr b=3> Reloading now...",1200).onHide(()=>location.href="");return!0}}}),_Xj=_we(function*(a){_9j._uy&&(yield _Ee("set",a));yield _Sp(a)});function _Ts(a){for(let [b,k]of _va(a))_Ts(k),_ul(k)&&(_Jw(a)?a.splice(b,1):k&&"object"==typeof k&&"value"==b&&a.name||delete a[b]);return a}
let _8s=_we(function*(){if((yield _ru("trigActList")).length||!_ul(_Ts(yield _ru("customEntities"))))return!1;let a=_Ts(yield _ru("mouseGest"));return!_ji(a,"triggers","preconds")&&(!_ji(a,"triggers","begin")&&!_ji(a,"triggers","end")||"other"!=_ji(a,"triggers","preset"))});
function _K(a,b,k,g){function m(c,e){for(let d=1;;++d)if(!(d in c||d in e))return d}function v(c,e,d){c.trigActList.del(e);for(let [f,h,q]of _Dr(c.customEntities.menuSpec))"type"==f&&"action"==h&&q.content==e&&(q.content=+d)}function x(c,e,d,f,h){h||(c.customEntities[e][f]=c.customEntities[e][d]);delete c.customEntities[e][d];d=e+":"+d;e=e+":"+f;e=JSON.stringify(_bj(c)).replace(RegExp(`"${d}"`,"g"),`"${e}"`);c.add(_Qj(JSON.parse(e)))}function l(c,e){return 0==_Vo(_Ha(c),_Ha(e))}function r(c,e,d=0){return JSON.stringify(e).replace(/"([a-z]+):(\d+)"/ig,
(f,h,q)=>(h=15>d&&_ji(c.customEntities[h],q,"value"))?'"'+r(c,h,d+1)+'"':f)}function n(c,e){return r(a,c)==r(b,e)}function t(){do{var c=!1;for(let e of Object.keys(b.trigActList)){let d=b.trigActList[e];for(let [f,h]of a.trigActList)!d.disabled&&h.disabled||h.title&&d.title&&!l(h.title,d.title)||!n([h.triggers,h.actions],[d.triggers,d.actions])||(c=!0,v(b,e,f),!h.title&&d.title&&(h.title=d.title),!h.icon&&d.icon&&(h.icon=d.icon))}}while(c)}function p(c,e,d){for(let [,f]of d)f.sctnId==c.id&&(f.sctnId=
e);c.id=e}function w(){for(let [c,e]of _va(b.sections))for(let d of a.sections)l(e.name,d.name)&&(p(e,d.id,b.trigActList),b.sections.splice(c,1))}for(let [,c]of a)_Ts(c);for(let [,c]of b)_Ts(c);(function(){for(let [c,e]of b.trigActList)if(a.trigActList.has(c)){let d=m(b.trigActList,a.trigActList);b.trigActList.set(d,e,b.trigActList.getPos(c));v(b,c,d)}})();(function(){a:for(;;){for(let [e,d]of b.customEntities)for(let [f]of d){var c=a.customEntities[e]||{};if(f in c){c=m(d,c);x(b,e,f,c);continue a}}break}})();
g&&t();(function(){a:for(;;){for(let [c,e]of b.customEntities)for(let [d,f]of e)if(f.name)for(let [h,q]of a.customEntities[c]||{})if(l(f.name,q.name)){if(n(q.value,f.value))x(b,c,d,h,!0);else{let y=f.name.replace(/\((\d+)\)$/,(z,u)=>`(${+u+1})`);l(y,f.name)&&(y=f.name+" (2)");b.customEntities[c][d].name=y}continue a}break}})();(function(){let c=b.sections.reduce((d,f,h)=>(d[f.id]=h,d),{}),e=a.sections.reduce((d,f,h)=>(d[f.id]=h,d),{});for(let d of b.sections)if(d.id in e){let f=m(c,e);p(d,f,b.trigActList)}})();
k&&w()}function _4p(a,b,k=!1){a.trigActList=k?b.trigActList.add(a.trigActList):a.trigActList.add(b.trigActList);a.sections.push(...b.sections);for(let [g,m]of b.customEntities)_lf(a.customEntities,g).add(m);for(let [g,m]of b.toolbarBtns)_ji(a.toolbarBtns[g],"icon","img")||(a.toolbarBtns[g]=m);return a};
