'use strict';const _Th=0,_wi=1,_Se=2,_Pp=3,_mp=4,_tj=5,_Ag=6,_qs=7,_Yf=8,_er=1,_ot=2,_vi=10,_1t=3,_2k=4,_ca=5,_8=6,_5a=7,_T=8,_Ku=9,_5=11,_Zu=12,_0y=13,_bt=14,_2j=15;let _pg={},_su,_uk={};
{let p,w,N,O,P,G,H,Q;var _mh=function(c,a={},d){p={map:{},list:[],urlTests:[],combinSequences:{},gestures:[],neededCaretSt:0};w={trigRepTime:.6,trigStepTime:1.5}.add(d);w.dfltWldcrd=null==w.dfltWldcrd?_Ds:+w.dfltWldcrd;_lf(w.dfltGestPreconds=a.preconds||{},"chromeState",{active:1});P=O=N=0;G=[{},{}];_Fy=H=!1;_uk={};_su=parseInt(_Tj.substr(22,2),36);for(let [h,m]of c)m.disabled||K(m.triggers||[],{type:_wi,param:+h+_su});_ji(a,"begin",0,"combins","length")&&_ji(a,"end",0,"combins","length")&&(K(a.end,
{type:_mp,state:!1}),K(a.begin,{type:_mp,state:!0,timeout:a.timeout}));c=p;w=G=p=null;return c};let K=function(c,a){Q=0;for(let d of c)_Bw(d)||R(d,a)},n=function(c,a,d=[],h=[],m="back"){m=m.split(" ");a=a.sc();let k=p.list.push(a)-1;a.preconds=X(d,h,k,"noExtraActions".in(m));0==a.preconds.length&&delete a.preconds;c=S(c);for(let l of c)_lf(p.map,l+20200+1825,[])["front".in(m)?"unshift":"push"](k);return k},Y=function(c){c={part:c.part,regex:_Gt(c.value,c.type).source};let a=_ki(p.urlTests,c);-1==
a&&(a=p.urlTests.push(c)-1);return a},X=function(c,a,d,h=!1){let m=[],k=[],l=[],t={};for(let b of c.concat(a)){a=null;if(b.urlTest)b.urlTest.value&&(a={type:_1t,testIdx:Y(b.urlTest)});else if("chromeState"in b)a=b.chromeState||{},a=[void 0,{type:_ot,value:1},{type:_ot,value:0},{type:_vi,value:1},{type:_vi,value:0},{type:_ot,value:0,negate:!0},{type:_ot,value:1,negate:!0},null][(a.active?1:0)|(a.inactive?2:0)|(a.closed?4:0)];else if(b.menuState)a={type:_0y,menuNum:_lk(b.menuState.menuId)};else if(b.caretState){var f=
b.caretState;f.off&&f.on&&f.omnibox||(a={type:_Zu,value:f.off|f.on<<1|f.omnibox<<2},p.neededCaretSt|=a.value)}else b.mouseOver?a={type:_bt,value:b.mouseOver.region}:b.swtchState?(f=b.swtchState,f.swtchId&&(a={type:_ca,swtchId:+_wh(f.swtchId)[1],state:f.state,oper:_Ah(f.oper)})):b.wildcard?(f=b.wildcard==_Ds?w.dfltWldcrd:b.wildcard)&&(a={type:_8,value:f}):"keyStateChange"in b?a={type:_Ku,value:+b.keyStateChange}:b.prevSeqStep?a={type:_2k,maxTime:b.maxTime}.add(b.prevSeqStep):"actionState"in b?a={type:_5a,
value:b.actionState,actIdx:b.actIdx}:"actionDone"in b?a={type:_T,value:+b.actionDone,actIdx:b.actIdx}:b.mouseGestState?a={type:_5,value:b.mouseGestState}:b.clipFmt?a={type:_2j,value:b.clipFmt}:b.keyEvt&&(f=_eh(b.keyEvt,!0),f.isDownUp&&!f.miscNum&&(b.keyEvt=f.num|f.type),a=S(b.keyEvt),a={type:_er,key1:a[0],key2:a[1],toggleState:b.toggleState},_5u(f)&&(p.usesJoystk=!0),!h&&b.block&&L(f)&&!b.toggleState&&(f=n(b.keyEvt,{type:_Th,block:!0},c),n(b.keyEvt,{type:_Ag,actIdx:d},T(c),[{keyStateChange:!0}]),
p.list[d].type.in(_Yf,_Pp)||(n(b.keyEvt|_mk,{type:_Se,param:_Ah("Y")},E(c),[{actionDone:!0,actIdx:f},{actionState:_Ah("D"),actIdx:d,negate:!0}]),b.block==_sa&&n(b.keyEvt|_mk,{type:_Th,block:!0},E(c),[{actionDone:!0,actIdx:f},{actionState:_Ah("D"),actIdx:d}]))));if(a){f=+b.negate==_Zy;if(+b.negate&&!f||"not"==b.oper)a.negate=!0;!a.type.in(_1t,_0y,_bt)||a.negate||f||"and"==b.oper?a.type==_bt?k.push(a):a.type==_ca?l.push(a):m.push(a):_lf(t,a.type,[]).push(a)}}l.length&&(l[l.length-1].mark=_Ah("S"));
c=[];for(let [,b]of t)1==b.length?c.unshift(b[0]):(b[0].mark=_Ah("F"),b[b.length-1].mark=_Ah("L"),c.push(...b));return m.concat(l,c,k)},Z=function(c){const a={[_Ap]:Symbol(),[_Io]:"domain",[_uj]:"mainDomain",[_Vr]:"path"};let d=[];for(let h of c)if(h.value)d[h.negate?"unshift":"push"]({part:a[h.part],regex:_Gt(h.value,h.type),negate:h.negate});return h=>{let m=_Eh(h),k=[];for(let f of m){a:{var l=_m[f]||_zh(_Yp[f]);for(let b of d){var t=b.negate;if(b.regex.test(b.part==a[_Ap]?l:_pe(l,b.part))==(b.negate!=
_Zy)){l=!b.negate;break a}}l=t}l&&k.push(f)}return k.length?m.length==k.length?h:_qt(null,{tabs:k}):!1}},aa=function(c){let a=[];for(let d of c||[])if(d.mouseMove&&(c=p.gestures.indexOf(d.mouseMove),-1==c&&(c=p.gestures.push(d.mouseMove)-1),d.eventId=c|_th),a.push(d),1<+d.repCount){c=d.sc().del("negateSeq").add({maxTime:w.trigRepTime});for(let h=1;h<+d.repCount;++h)a.push(c)}return a},R=function(c,a){const d=_ty(c),h=a.sc(),m=++N,k={},l=aa(d.combins);var t={seqId:m,stepId:0};let f=!1;_lf(d,"preconds");
for(var b=0;b<l.length;++b){let e=l[b];if(!e.eventId)continue;let g=_eh(e.eventId,!0),z,B=[];if(g.type==_cf){if(g.num==_vt)B.push({clipFmt:e.clipFmt}),e.diffCont&&(e.eventId=_C|_cf,g=_eh(e.eventId,!0));else if(g.num==_1s){if(!e.evtName)continue;_lf(p,"extEvtNames")[e.evtName.trim().toUpperCase()]=e.eventId-=P++;g=_eh(e.eventId,!0)}else _rj(g.num)&&e.btnId&&(e.eventId=e.btnId,e.block=e.btnId<_Ze?_h:_sa,z={mouseOver:[{region:_Hh+1+g.num-_At}]},g=_eh(e.eventId,!0));g.num<_vt&&(_uk[g.num]=!0)}else g.type==
_th&&(f=!0);let I=L(g);g.isDownUp&&!g.miscNum&&(e.eventId=g.num|g.type);var A=b==l.length-1;let C=U(e),u=ba(e,g),ca=u?U(u):void 0;_5u(g)&&(p.usesJoystk=!0);1<l.length&&(k[g.devId]=1,k.add(C),f&&(k[_cj]=1));const r=A?e.noAutoRep&&I&&g.devId==_ee?h.add({autoRep:!1}):h:{type:_qs,param:{seqId:m,stepId:b+1}};r.block=!!e.block;r.PBC=C;if(0==b)if(f)for(let [y,x]of w.dfltGestPreconds)_lf(d.preconds,y,x);else _lf(d.preconds,"chromeState",{active:1,inactive:g.type==_cf||e.btnId});const M=r.type==_mp&&r.state,
V=r.type==_mp&&!r.state;M&&(B.push({mouseGestState:_Ah("S")},{keyStateChange:!0}),d.preconds=_Ni(G));V&&(B.push({mouseGestState:_Ah("S"),negate:!0},{keyStateChange:!0}),d.preconds={},delete e.wildcard);let v=[];var q=z?Object.assign({},d.preconds,z):d.preconds;for(let [y,x]of q)if(x){if("urlTests"==y)y="urlTest";else if("menuState"==y)x=d.preconds[y]=_hw(x);else if("evtUrl"==y){A&&g.type==_cf&&g.num<_Ay&&(r.param|=++Q<<24,_pg[r.param]=Z(x),_Fy=!0);continue}_Jw(x)||(x=[x]);for(let W of x)v.push(W.sc().keep("negate",
"oper").add({[y]:W}))}0==b&&g.isDownUp&&g.num==_qe&&(_ul(e.preconds)||1==C[_xe]&&1==Object.keys(C))&&(q=H?{mouseOver:{region:_Si},negate:!0}:{urlTest:{part:_Ap,type:"starts",value:_Yk.runtime.getURL(_ak)},negate:!0},v.push(q),H^=1);const F=I?e.holdPeriod|0:0;1<l.length&&(0<b||da(e.eventId,l.slice(1))&&!l[b+1].negateSeq)&&v.push({prevSeqStep:t,negate:e.negateSeq,maxTime:1E3*(e.maxTime||w.trigStepTime)+F});t=_Ii(e.preconds||[],e.wildcard?{wildcard:+e.wildcard}:[]);let J=e.eventId;F&&(J=++O|_Uh);A&&
1<l.length&&n(J,{type:_qs,param:{seqId:m,stepId:b+1},PBC:C},v,t,"noExtraActions");q=n(J,r,v,t.concat(B));var D=void 0;F&&(D=r.sc().del("param").add({type:A&&!e.noAutoRep?_Pp:_Yf,evtId:J,delay:F}),D=n(e.eventId,D,v,t.concat(B)),n(u.eventId,{type:_tj,actIdx:D}));e.block==_sa&&_Ys(g)&&(A={type:_Th,block:!0},I?n(u.eventId,A,[],[{actionDone:!0,actIdx:q}]):n(u.eventId,A.add({PBC:ca}),v,t.concat(B)));if(r.block&&I){n(u.eventId,{type:_Se,param:_Ah("N")},[],[{actionState:_Ah("D"),actIdx:q}]);if(M||V)n(e.eventId,
{type:_Th,block:!0},E(v),[{actionState:0,negate:!0,actIdx:q},{keyStateChange:!1}]),M&&(n(u.eventId,{type:_Se,param:_Ah("Y")},[],[{mouseGestState:_Ah("S")},{actionState:_Ah("I"),actIdx:q}]),n(u.eventId,{type:_Th,block:!0},[],[{mouseGestState:_Ah("S")},{actionState:_Ah("D"),actIdx:q}]),n(u.eventId,{type:_Ag,actIdx:q},[],[{mouseGestState:_Ah("S")},{actionState:0,actIdx:q,negate:!0}]));F&&(n(u.eventId,{type:_Se,param:_Ah("Y")},E(v),[{actionDone:!0,actIdx:D},{actionState:_Ah("D"),actIdx:q,negate:!0}]),
n(u.eventId,{type:_Th,block:!0},E(v),[{actionDone:!0,actIdx:D},{actionState:_Ah("D"),actIdx:q}]))}g.isDownUp&&n(e.eventId,{type:_Ag,PBC:C,actIdx:q},T(v),[{keyStateChange:!0}],"noExtraActions front");t=r.param}if(f){const [e,g]=G;d.preconds.chromeState||(_Ot("emptyChromeState",{triggerObj:d,origTriggerObj:c,origActionData:a}),d.preconds.chromeState={});_lf(e,"chromeState").add([...d.preconds.chromeState].filter(([,z])=>z));null!==e.caretState&&(d.preconds.caretState?_lf(e,"caretState").add([...d.preconds.caretState].filter(([,
z])=>z)):e.caretState=null);_oh("urlTests",e,g,d.preconds);_oh("menuState",e,g,d.preconds);_oh("mouseOver",e,g,d.preconds);_oh("swtchState",e,g,d.preconds)}1<l.length&&(p.combinSequences[m]={usedDevs:Object.keys(k).map(e=>+e),lastStepId:b});H&&R(c,a);return q},S=function(c){let a=_eh(c,!0);if(!_Ys(a))return[c];let d=(_By[a.num]||[])[1];if(_Jw(d)){c=[];for(let h of d)c.push(h|a.type);return c}return[c]},L=function(c){return _Ys(c)&&c.type==_Lo},ba=function(c,a){if(_Ys(a))return c.sc().add({eventId:c.eventId^
_mk})},E=function(c){return c.filter(a=>!a.prevSeqStep)},T=function(c){return c.filter(a=>!a.mouseOver)},U=function(c){let a={},d=function(k){L(k)&&(a[k.devId]=(a[k.devId]||0)+1)},h=_eh(c.eventId,!0);d(h);let m;for(let k of c.preconds||[])k.toggleState?m=!0:d(_eh(k.keyEvt,!0));!a[h.devId]&&_Ys(h)&&h.type==_mk&&(a[h.devId]=-1);m&&!a[_ee]&&(a[_ee]=-1);return a},da=function(c,a){for(let d of a)if(d.eventId==c)return!0;return!1}};
