'use strict';var _Nd,_Ey,_pi;
{let v=function(){_Gu("customEntities.*",(a,b)=>void 0+(_9j._if[b[1]]=_ji(a,...b)));_Gu("customEntities.menuStyle",(a,b)=>void 0+_9j._8a(_ji(a,...b)));_B("customEntities.binSwtch.*",(a,b)=>_Ho&&e(!0));_B("customEntities.tse","trigActList.*.actions",(a,b)=>void 0+_9j._zj(a));_B("customEntities.menuSpec","previewMakerParams","trigActList.*.actions",(a,b)=>void 0+_9j._6s(a));_B("trigActList.*.triggers","mouseGest.triggers",(a,b)=>void 0+_9j._no(a));_B("trigActList.*.disabled","trigActList.*.",(a,b)=>
void 0+_9j._Gf(a)+_6r(a));_Gu("mouseGest.params",(a,b)=>void 0+_9j._Jp(_ji(a,...b)));_Gu("mouseGest.display",(a,b)=>void 0+_9j._6t(_ji(a,...b)));_Gu("toolbarBtns",(a,b)=>_Ho&&_Ew(_ji(a,...b)));_Gu("sections",(a,b)=>_Ho&&$("body").toggleClass("hasSectns",a[b[0]].length));_Gu("advOpts.*",(a,b)=>{"ignInjInp"==b[1]?_9j._Jf(a[b[0]]):_9j._no(a)});_Yk.storage.onChanged.addListener((a,b)=>{"local"==b&&(b=_ji(a,"LOCAL","oldValue","switchStates"),(a=_ji(a,"LOCAL","newValue","switchStates"))&&JSON.stringify(a)!=
JSON.stringify(b)&&e())})};var _Wt={actions:{templ:"trigActsPanel",func:_bk},options:{templ:"optionsPanel",func:_lg},help:{templ:"helpPanel"}};let h,e=_Es(300,function(a=!1){let b=[..._Xy("binSwtch",!0)].map(k=>{let l=_wh(k)[1];return`<swt entId=${l}><name spellcheck=false>${_gh(k).name}</name><st val=${_9j._ps[l]|0} title="Click to toggle"></st></swt>`}).join("");var c=$("tabs > switches");let d=c.hasClass("visible");c=c.toggleClass("visible",!!b).find("> cont").html(b);a&&(_9j._nk(),h||!b||d||(h=
!0,_3p("<c>Rename your switch here.</c>",c,"rbt","infoBubble small","","opacity")))}),w=function(){$("body > tabs").on("mousedown","tab:not([active])",function(){_Tp(this)();this.noNameEdit=!0}).on("mousedown","sectns > tab",function(a){let b;$(document.body).on("mouseenter.sectnTabDrag","sectns > tab:not([active])",c=>{let d=this.getBoundingClientRect();_5d(this,c.clientY<d.top?-1:1,200);b=!0}).on("mouseup.sectnTabDrag",()=>{$(document.body).off(".sectnTabDrag");b&&$(this).triggerEvt("change",!0)})}).on("click",
"sectns tab[active]",function(){this.noNameEdit||_ua($("name",this)[0]);delete this.noNameEdit}).on("focusout","name",function(){this.innerText.length||(this.innerText="\u2639");this.innerText=this.innerText.replace(/[\r\n]+/g," ").slice(0,50);$(this).triggerEvt("change",!0);this.contentEditable=!1;getSelection().removeAllRanges();this.scrollLeft=0}).on("change","> sectns",function(){_Mi(_1j(this),_fw(this))});$("body > tabs > switches").on("mousedown","st",function(){_9j._2t(+$(this).parent().attr("entId"),
!+$(this).attr("val"))}).on("click","name",function(){_ua(this)}).on("keydown","name",function(a){13==a.keyCode&&this.blur()}).on("change","name",function(){this.innerText=_Ha(this.innerText);let a="binSwtch:"+$(this).parent().attr("entId");_1e([a,"name"],this.innerText,0);$(`[value='${a}'] > l`).text(this.innerText)})};var _vu="actions";let p=_cg(function*(){v();_7u();_Xf();w();window.onbeforeunload=function(){$(document.body).triggerEvt("mousedown")};let a="AutoControl configuration";"function"==
typeof customizeVariant&&([a,_vu]=yield customizeVariant());document.title=a;(yield _Yd(_9j._Eu.wait(),_za(500)))||($("html").css("display","block"),_Lg(),yield _Yd(_9j._Eu.wait(),_za(3E3)),_Lg(!1));_9j._nd?($(document.body).is(".msgWin")||m(3,500)(b=>{b||(_We(_a("natHostNotFound"),{title:"Native Component not working",icon:"error",width:"initial",nearMouse:!1})(c=>{"reload"==c?_9j._co(2,!0):"reinstall"==c&&f()}),_Ot("NH-noConnex"))}),_Uy&&!(yield _Uy.afterLoad())||n()):($("html").addClass("visible"),
x())});_Li(document.fonts.load("25px logoFont"),document.fonts.load("12px symbols"),document.fonts.load("15px gestureDirs"),a=>_9w("AutoCtrl/file86.js",a),a=>_4h("AutoCtrl/file46.css",a),_Hu.wait())(p,p);var _rg=_we(function*(){let a=_xk(yield c=>_Yk.storage.local.get(null,c)),b=$("body > tabs > perms > cont");b[0]&&b.html(yield _ct(a.filter(c=>"bg"!=c)));return a}),_8f=_we(function*(a){let b=yield c=>_9i({toolbarBtns:{},sections:[]},c);_Ew(b.toolbarBtns);$("body > tabs > sectns").html(b.sections.map(_dt).join(""));
$("body").toggleClass("hasSectns",b.sections.length);e();(a=$(`body > tabs [pnlId='${a}']`)[0])&&(yield _Tp(a));return yield _rg()});let n=_cg(function*(a=!1){var b=_Ko(location);b?(document.title="Script Editor - AutoControl",yield _yf("file29.html",!0),$("html").css("display","block"),yield _G(b,!0),$("html").addClass("visible")):(b=(location.hash||"").slice(1)||(_Uy?_hp(_ji((yield _ru("trigActList"))[Symbol.iterator]().next().value,1,"sctnId")):_vu),b=yield _8f(b),$("html").addClass("visible"),
yield _za(600),yield _Qk(b,"permMsgs/missing",!0),yield _za(1E3*(a?180:5)),a=$("<contribBtn>Support<br>the project</contribBtn>").appendTo("body > tabs").click(()=>{let c=_Zd("Support the Project",_a("contribPanel"),"",!1,!0);$("[contribPanel]",c)[0].scrollTop=0}),yield c=>_ed(c),a.addClass("onview"),yield _za(1700),q(),setInterval(q,6E4))}),q=()=>{let a=$("contribBtn").addClass("animate");setTimeout(()=>a.removeClass("animate"),2E3)},y=0,r=0,f=_cg(function*(a=0){if(!(3E3>Date.now()-r)&&(r=Date.now(),
_Ot("NH-dwnld",{method:a}),5.1<=_Ie&&11>_Ie&&/^win/i.test(navigator.platform)||(yield _Ng("",_a("unsupportedOS"),{yes:"Try installing anyway",no:"Cancel",icon:"info",width:"initial"})))){switch(a){case 0:_2o(_or,yield _3t(_7i,"blob"))}$("runInstPane")[0]||_a("runInstPane").appendTo("body");3==++y&&setTimeout(()=>_u(_a("installTrouble"),{width:"initial"}),3E3);yield _za(4E3);$("runInstPane").addClass("visible");t();yield _za(3E3);$("installPane ques[help]:not(.open)").each((b,c)=>u(c));yield _za(400);
$("install").each(function(){this.scrollIntoView({behavior:"smooth"})});yield _za(3E4);$("runInstPane").remove()}}),m=_we(function*(a,b){for(let c=0;c<a;++c){let d=yield _9j._Vy(_xp,"",b);if(void 0===d)yield _za(b);else if("pong"==d)return!0}return!1}),g,t=function(){g||(g=!0,m(Infinity,1E3)(()=>{g=!1;z()}))},u=a=>{let b=function(){$("+ answ",this).css("width",this.offsetWidth).slideToggle(300,function(){});$(this).toggleClass("open")};$(a).siblings("ques.open").each(b);b.call(a)},x=()=>{let a="",
b=()=>_u(_a("natHostInit"),{width:"initial",nearMouse:!1});$("head title").addClass("notranslate").append(" - Native Component");$(document.body).addClass("installPane");_a("installPane").on("click","install",()=>f(0)).on("click","a[install]",()=>f(3)).on("click","installPane",()=>$("runInstPane").remove()).on("mousedown","faq > ques",function(){u(this)}).on("keypress",c=>{a=(a+String.fromCharCode(c.which)).slice(-10);"NH-INSTALL"==a&&(_Ot("NH-install"),$("runInstPane").remove(),b())}).appendTo("body");
_9j._dh&&setTimeout(()=>{b();t()},600)},z=()=>{$("installWrap").off("keypress");_gs("dialog");$("installPane, runInstPane").remove();$("installWrap")[0]&&(n(!0),setTimeout(()=>{$("installWrap").fadeOut(1E3,function(){this.remove();$("body").removeClass("installPane")})},350))}};
