'use strict';const _9j=_Yk.extension.getBackgroundPage();_Ie=_9j._Ie;const _rt="chrome://extensions/?id="+_Tj;
_4a.add({reviews:_4a.chromeWS+_Tj+"/reviews",faq:_Zo+"faq",triggers:_Zo+"triggers",actions:_Zo+"actions",mruTabs:_Zo+"switch-to-last-used-tab-in-chrome",installer:_Zo+"files/"+_or,natComp:_Zo+"native-component",tbBtns:_Zo+"custom-toolbar-buttons",domTabs:_Zo+"sort-group-close-tabs-by-domain",actMenu:_Zo+"action-menus",relseRam:_Zo+"release-ram-without-closing-tabs",chromeBugs:_Zo+"chromium-bugs",updHist:_Zo+"update-history",scrtDoc:_Zo+"scripting",omboxShrt:_Zo+"address-bar-shortcuts",mseHvrShrt:_Zo+
"hover-sensitive-shortcuts",donate:_Zo+"donations",winSecExcl:"https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security",fileAcc:_rt+"#:~:text=Allow%20access%20to%20file%20URLs",incogAcc:_rt+"#:~:text=Allow%20in%20Incognito"});function _Qf(){let a=[];for(let [b,c]of _9j._Zw)a.push([b,c.name]);return a}
let _ct=_we(function*(a){let b=yield _ff("/permns");return a.map(c=>`<c h=/permns/${c}/1>${b[c][0]}</c>`).join("")}),_Qk=_we(function*(a,b,c){let d=yield g=>_Yk.permissions.getAll(g),e={bkm:"bookmarks",ses:"sessions",bg:"background",notf:"notifications",dwld:"downloads",hst:"<all_urls>"},f={},h=[],l;"string"==typeof a&&(a=a.trim().split(/\s+/));for(let g of a){a="hst"==g?"origins":"permissions";let k=e[g];0>d[a].indexOf(k)&&("bg"!=g||c?(_lf(f,a,[]).push(k),h.push(g)):l=!0)}c=!0;if(!_ul(f)){let g=
`${yield _ff(b)} <permReqLst>${yield _ct(h)}</permReqLst>`;yield k=>_u(g,{},k);b=Date.now();(c=yield k=>_Yk.permissions.request(f,k))&&100>Date.now()-b&&(yield _Rg("The permissions had already been granted. <hr b=2> All's well now.",1200).onShow,yield _za(500))}l&&_Yk.permissions.request({permissions:["background"]});return c});function _6r(a={}){_3d(a,b=>{_Yk.permissions[b?"request":"remove"]({permissions:["background"]},_Aw)})}
function _xk(a){var b={};let c={};for(let [,,d]of _Dr(a.trigActList))if("openMenu"==d.action&&_ji(d.params,"menuId")in _9j._Du.menuSpec)b[d.params.menuId]=_9j._Du.menuSpec[d.params.menuId];else if("saveUrl"==d.action||"saveElemUrl"==d.action)switch(d.params.method){case "notif":c.notf=!0;break;case "dwnlApi":c.dwld=!0}else if("runScript"==d.action&&!d.params.bkgrnd||"sendInput"==d.action&&_ji(d.params,"intoPage")||_Xt(d.action,"copyElemUrl","openElemUrl","saveElemUrl"))c.hst=!0;b=JSON.stringify([a,
b]);/"type":"closedTabs"|"action":"(undoClose|reopen)"/.test(b)&&(c.ses=!0);/"type":"bmFolder"|"action":"(openBookmarks|bookmarkTabs)"/.test(b)&&(c.bkm=!0);_3d({trigActList:{},mouseGest:{}}.add(a),d=>{d&&(c.bg=!0)});return Object.keys(c)}function _4i(a,b,c,d,e){$("body > tabs")[0].insertBefore($(`<tab pnlId="${b}" ${d}>${c}</tab>`)[0],$(`body > tabs > tab[pnlId='${a}']`)[0]);_Wt[b]={func:e}}
let _Vd=()=>a=>{let b=[],c=new _wk(()=>a(b.sort()));for(let [d,e]of _gj.entries())_Yk.runtime.sendMessage(e,"ping",c.onReady(f=>!_Aw()&&"pong"==f&&b.push(d)))};function _Ew(a){let b="";for(let c in a)b+=`[iconUID=TBBtn${c}]::before {background-image: url(${_ji(a[c],"icon","img")})} \n`;$("style[tbBtnIcons]").html(b)}function _Jt(a){return a+1-(4<a?4:0)}
let _Wp=new _Wf,_Tp=_we(function*(a){if(!$(a).is("[active]")){a=$(a).attr("pnlId");let b=$(`body > content > panel[pnlId='${a}']`)[0];if(!b){let [,c,d]=a.match(/^(.+?)(?::(\d+))?$/);b=$("<panel>").attr(c,"").attr("pnlId",a).css("pointer-events","none").appendTo("body > content")[0];let e=_Wt[c];e.templ&&$(b).append(_a(e.templ));e.func&&(yield e.func(b,d));setTimeout(_cg(function*(){yield f=>_ed(f);yield _za(250);yield _zf(!0);_Wp.send("",!0);$(b).css("pointer-events","")}))}$("body > tabs tab, body > content > panel").attr("active",
null).filter(`[pnlId='${a}']`).attr("active","");location.hash=a;return b}}),_yf=_we(function*(a,b){document.body.insertAdjacentHTML("beforeend",`<import src="${a}"></import>`);yield _zf(b)});function _xf(a){_Ad()(b=>{_Ee("clear",b)(()=>{a(b)})})}function _hp(a){return"actions"+(a?":"+a:"")}
var _lj=_we(function*(a,b,c=[],d=!1,[e,f]){if(yield _Qk(_xk(a),"permMsgs/impSttgs",!0))yield h=>_bd(a,h),yield h=>_9j._ku(h),_ul(c)&&(e=f?`<b>${e}</b> out of ${e+f} actions were successfully imported. <hr b=4> <b>${f}</b> actions were not imported for being identical <br> to existing actions.`:"Settings imported successfully.",d||f?_u(e,{type:"success"}):_Rg(e,1200)),_Ud()(),$("body > content > panel").remove(),$("body > tabs > tab").attr("active",null),yield _8f(_hp(b)),c.forEach(h=>$(`trigAct[actionId='${h}']`).addClass("selected")),
_Oi($("trigActList")[0])});const _2d=_Oo({trigActList:[],customEntities:{},toolbarBtns:{},sections:[]});
let _uw=_cg(function*(a,b=!0,c=!1,d=!1,e=!1,f=!0){let h=a.trigActList.length;const l=yield g=>_9i(_2d,g,chrome);_K(l,a,b,f);b=a.trigActList.length;c=c?Object.keys(a.trigActList):[];f=_ji(a.trigActList[Symbol.iterator]().next().value,1,"sctnId");a=_4p(l,a,d);yield _Xp(yield _0j())._lj(a,f,c,e,[b,h-b])}),_kp=_cg(function*(a,b,c=!1){try{var d=JSON.parse(a)}catch(e){_u("The file specified is not a valid AutoControl settings file.",{type:"error"});return}b||(b=(yield _8s())?"replace":yield _We(_a("askAddReplSettgs"),
{width:"initial"}));"replace"==b?yield _Xj(d):"add"==b&&(a=_Qj({}.add(_2d,d)),_uw(a,!0,!1,!1,c))});var _ja=_cg(function*(a){let [b,c]=yield _mg(_1p(a,"text"));200!=c.status?_u(`Error while opening the file. <hr b=2> "${a}" <hr b=2> ${_wu(c.status,c)}`,{type:"error"}):_kp(b,"add",!0)});
