'use strict';var _Ta;function _xt(a,b=!1){if(b){let c=_cd[_Yp[a].windowId];_Ms(c.id,!0,f=>{Object.assign(c,f);f=c.tabs.map(e=>e.id);if(1<f.length){_Ft.remove(a);let e=0;for(let d=0;d<_Ft.length;++d)if(0<=f.indexOf(_Ft[d])&&++e==f.length-1){_Ft.splice(d+1,0,a);break}}})}else _Ft.remove(a),_Ft.push(a)}let _tr={};function _qp(a,b=!1){1==_tr[a]?_tr[a]=2:(delete _tr[a],a!=_Ft[_Ft.length-1]&&_xt(a,b))}
function _hg(a,b,c=!1){let f=b.filter(e=>-1!=a.indexOf(e));if(f.length<a.length)f[c?"unshift":"push"](...a.filter(e=>-1==f.indexOf(e)));return f}
function _Fu(a){_Vt(!0)(b=>{_Gk=[];_Yp={};let c=_cd;_cd={};let f=[];for(let e of b)b=e.id,delete (_cd[b]=Object.assign(c[b]||{},e)).monitorId,f.push(b);_n=_hg(f,_n,!0);_ts=_hg(f,_ts);for(let e of _n)for(let d of _cd[e].tabs)d.id=_js(d),d.window=_cd[e],d.active&&(d.window.activeTab=d,e==_4t&&(_Np=d.id)),_Yp[d.id]=d,_Gk.push(d.id);_ea=_hg(_Gk,_ea,!0);a&&a()})}function _0o(a,b){b?(_Or[b]=+a,_na[a]=+b):(b=_na[a]|0,delete _Or[b],delete _na[a],_Lk(_1d,[b]))}
function _Sh(a,b,c,f){_Lk(_5t,{tabId:a,win:_na[b],time:c,popup:f})}function _0k(a,b){_Lk(_ta,{tabId:a,win:_na[b]})}let _jd,_gu;function _Ja(a){_gu&&a!=_jd&&_Lk(_yg,_jd=a)}const _Oj=parseInt(_Tj.substr(13,2),36);let _Le,_as,_2s=0;
function _y(a,b){a+=_Oj;if(a!=_2s){var c=_Or[_2s];c&&_Wy(c,e=>{e&&(_as&&_as.send(),_lf(_cd,c).focused=!1,_Wo(_Cw,c),_Wo(_Ed,e.id))});var f=_Or[a];_2s=f?a:0;f?(_ko=!0,_Wy(f,e=>{e&&(_4t=f,_Np=e.id,_lf(_cd,_4t).focused=!0,_qp(_Np),_Ja(_zh(e)),_Le&&_Le.send(),b||(_Wo(_Wk,_4t),_Wo(_vp,_Np)))})):a&&_Yk.windows.getAll({populate:!0,windowTypes:["devtools"]},e=>{for(let d of e)~_n.indexOf(d.id)||(_yh(d),_Zf(d.tabs[0]))})}}
function _v(a,b){if(0<b&&a.length>b){const c=a.charCodeAt(b-1);a=a.slice(0,b-(55296<=c&&56319>=c?1:0))}return a}function _Wy(a,b){_zg({windowId:a,active:!0})(c=>{c&&c[0]?(c[0].id=_js(c[0]),b(c[0])):_Hy(a,b)})}function _Hy(a,b){_Ms(a,!0,c=>{if(_Aw()||!c||!c.tabs)return b();for(let f of c.tabs)if(f.active)return f.id=_js(f),b(f)})}
{let a={};var _1f=function(b,c,f){!a[b]&&_na[b]&&(_Sh(0,b,f),b==_4t&&_Ja(_zh(_Yp[c])));clearTimeout(a[b]);a[b]=setTimeout(()=>{let e=a[b];_Yk.tabs.get(c,d=>{if(!_Aw()){if(e!=a[b])return;_na[b]&&_Sh(c,b);b==_4t&&_Ja(_zh(d))}delete a[b]})},300)}}let _ko=!0,_6i;
function _cr(a){_ko=!1;_ts=[];for(let b of a)(a=_Or[b])&&_ts.push(a);clearTimeout(_6i);_ts.length!=_n.length&&_Vt()(b=>{b=b.map(c=>c.id);_Kf(_n,b).forEach(_q);_n.length!=_ts.length&&(_6i=setTimeout(()=>{let c=_Kf(_n,_ts);c.length&&_Kp(c)},2E3))})}function _Kp(a){a.forEach(b=>_0o(b,void 0));_8u(a)(()=>{let b=_n.length;if(Object.keys(_Or).length!=b||Object.keys(_na).length!=b)_na={},_Or={},_Lk(_1d),_8u()(()=>{})})}function _bs(a,b,c){return"app"==c?a.endsWith(b):a.startsWith(b)}
function _oj(a){for(let b of a||_n)if(_na[b]){a=_ji(_cd,b,"tabs");for(let c of _ul(a)?[{id:0,active:!0}]:a)c.active?_Sh(c.id,b,void 0,"popup"==_cd[b].type):_0k(c.id,b)}}let _8u=a=>b=>{_Ry(a)(c=>{_oj(c);b&&b()})};
{let a=[];var _Ry=d=>k=>{a.push([d||_n,k]);1==a.length&&_ti(function*(){for(;a.length;){let [l,r]=a[0],t=yield c(l);Promise.resolve().then(()=>r(t));a.shift()}})};let b=[],c=_we(function*(d){var k=Date.now();d=d.filter(r=>!_na[r]);if(_7&&d.length){let r=(g,m)=>{q.remove(g);w.remove(m);if(u[m].parentHwnd){if(!_Ld[g]){_Ld[g]=!0;let h=_cd[g].activeTab;_fy(g);_Ot("hijackedWin",u[m].sc().add({id:h.id,url:_zh(h),title:h.title}))}}else _0o(g,m)},t=()=>{let g=u.sc().keep(...w),m={};for(let h of q){let n=
e(h,g),p=!1;for(let v of n)m[v]&&(delete m[v],p=!0);1!=n.length||p||(m[n[0]]=h)}for(let [h,n]of m)r(n,+h)},x=(g,m,h,n)=>{for(let p of g)if(0<=q.indexOf(p.id))for(let v of m)if(p.id==v.id){g=v.left-p.left;let B=v.top-p.top;if((h?(y=>0<y&&3>y)(g/h):g==h)&&(h?(y=>0<y&&3>y)(B/n):B==n))return p.id;break}},C=_we(function*(){[u]=yield _Li(_Vy(_uo,{refWin:Object.keys(_Or)[0]|0,inclHjkd:z}),g=>_Fu(g));(A[z|0]=u)&&(w=Object.keys(u).map(g=>+g).filter(g=>!_Or[g]))}),u,A=[],w,q,z;q=d.slice();a:{for(;;){yield C();
if(!u)break a;for(let g=0,m=!0;8>g&&q.length&&w.length;++g)if(m?m=!1:yield C(),t(),q.length){const h=(g%2*2-1)*(g>>1&1)*((g>>2)+1),n=(g%2*2-1)*(g+2>>1&1)*((g>>2)+1);for(let [,p]of _va(w)){var l=yield _Vt();yield _Vy(_ms,{win:p,x:h,y:n,noNotif:!0});let v=yield _Vt();yield _Vy(_ms,{win:p,x:-h,y:-n});(l=x(l,v,h,n))&&r(l,p)}}if(!z&&q.length)z=!0;else break}_ck(u);if(q.length&&_Kf(q,b).length){k=Date.now()-k;let [g,m]=yield _Li(_Vy(_Eo),_Vt(!0));m.forEach(h=>{(h.tabs=h.tabs.filter(p=>p.active)).forEach(p=>
p.keep("active","title","url","pendingUrl","width","height"));let n=_ji(_cd[h.id],"cTime");n&&(h.age=(Date.now()-n)/1E3)});(()=>{for(let h of q)for(let n of m)if(n.id==h){if(n.tabs[0])return!0;break}})()&&(k=_ty({ID_HWND:_na,HWND_ID:_Or,missingIds:q,unusedHwnds:w,data:f({winsData:m,hwndData:A[0],hjkdHwnd:A[1],allHwndData:g}),time:k}),_Ot("missingHwnds",k),q.forEach(h=>b.add(h)))}}}return d}),f=d=>{d=_pk(JSON.stringify(d),"UTF-8",!1);let k="";for(let l=d.length;0<l--;)k+=String.fromCharCode((d.charCodeAt(l)+
(1.3*(l+d.length)|0))%256);return btoa(k)},e=function(d,k){let l=_cd[d];d=[];if(l){for(let [t,x]of k)x.state==l.state&&_3s(l,x.coords)&&d.push(+t);let r=_ji(l,"activeTab","title");if(1<d.length&&r&&d.every(t=>k[t].title)){r=r.substr(0,200);let t=d.filter(x=>_bs(k[x].title,r,l.type));0<t.length&&(d=t)}}return d}}function _ck(a){if(a)for(let [b,c]of a)(a=_Or[b])&&(c.visible?_hd.remove(a):_hd.add(a))}
let _x=_la(),_5s=_cg(function*(){const a=_Yk.sessions;let b=_dg;_dg=[];let c=a&&a.getRecentlyClosed&&(yield e=>a.getRecentlyClosed({maxResults:Math.min(b.length,a.MAX_SESSION_RESULTS)},e))||[],f={};for(let e of b){let d=_ji(_Yp,e.id,"url");if(d)a:for(let k of c){if(1.5<e.time-k.lastModified)break;for(let l of k.tab?[k.tab]:k.window.tabs)if(d==l.url){_Ek&&(f[e.id]=+l.sessionId);k.tab&&(_x.length>=a.MAX_SESSION_RESULTS&&_x.delPos(0),_x[l.sessionId]=_Yp[e.id].windowId);break a}}f[e.id]+=0}_Lk(_Ia,f)});
