'use strict';const _p=document.currentScript.parentElement;function _u(a,b={},h=_ay){let l=_a("basicForm",{},_p).addClass(b.type||"info").addClass(!1===b.btn?"noBtn":"").append(_a("messageForm",{},_p));l.find("msg").css("maxWidth",b.width||"").append(a);l.find("button").click(function(){_gs(this);h()});return _Zd(b.title||"",l,"noClose",b.nearMouse,!0)}
function _Ng(a,b,h={}){return l=>{var k=_a("confirmForm",{},_p).addClass(h.icon||"confirm");k.find("msg").css("maxWidth",h.width||"").append(b);let q=k.find("button[accept]").html(h.yes||"Yes")[0];k.find("button[cancel]").html(h.no||"No");$("button",k).click(function(){l($(this).is("[accept]"),_fw($(this).closest("form")[0]))||_gs(this)});h.enterOk&&k.keydown(f=>{13==f.keyCode&&q.click()});return _Zd(a,k,"noClose",h.nearMouse,!0)}}
function _We(a,b={}){return h=>{a=_a("basicForm",{},_p).addClass(b.icon||"confirm").append(a).on("click","button[value]",function(){let l=this.value;_gs(this);h(l)}).find("msg").css("maxWidth",b.width||"").end();return _Zd(b.title,a,"",b.nearMouse,null==b.modal?!0:b.modal)}}function _gs(a,b=!0){$(a).closest("dialog").triggerEvt({close:b})}function _Zd(a,b,h="",l=!0,k=!1){return _Bt(a,b,h,!1,null,l&&"mouse").Show(k)}
{let a=[];var _Rg=function(b,h){b=[b,h,new _Wf,new _Wf];a.push(b);1==a.length&&_ti(function*(){for(;a.length;){let l=_u(a[0][0],{type:"success",btn:!1});a[0][2].send("",!0);yield _za(a[0][1]);_gs(l);a[0][3].send("",!0);a.shift()}});return{onShow:b[2].wait(),onHide:b[3].wait()}}}
function _Bt(a,b,h,l,k,q){const f=_a(l?"dialog2":"dialog",{},_p).appendTo("body").addClass(h).submit(!1).on("click","button",c=>c.preventDefault()).on("close",function(c,m){if(!c.originalEvent.defaultPrevented||m)this.remove(),_0t()}).on("dialogOpen focusGained focusLost",function(c,m){var p=$(this).hasClass("active"),n="focusLost"==c.type;"dialogOpen"==c.type&&_Qy(this);(n=p&&n||!p&&!n)&&$(this).toggleClass("active",!p);(n||"focusGained"==c.type&&"force"==m)&&$((l?"diagFrm":"")+"> content > *",this).triggerEvt(c.type)});
if(l)f.on("mousedown","> row > [d]",function(c){c.preventDefault();if(!f.is(".maximized")){$(document.body).css("pointer-events","none").parent().css("cursor",$(this).css("cursor"));var m=c.clientX,p=c.clientY,n=f[0].getBoundingClientRect();c={t(d,e,g){d.top+=g;r=!0},l(d,e,g){d.left+=e;u=!0},r(d,e,g){d.right+=e},b(d,e,g){d.bottom+=g},tl(d,e,g){this.t(d,e,g);this.l(d,e,g)},tr(d,e,g){this.t(d,e,g);this.r(d,e,g)},bl(d,e,g){this.b(d,e,g);this.l(d,e,g)},br(d,e,g){this.b(d,e,g);this.r(d,e,g)}};var t=c[$(this).attr("d")].bind(c),
r,u;$(document).on("mousemove.diagRedim",d=>{const e=n.sc();r=u=!1;t(e,d.clientX-m,d.clientY-p);f.css({width:Math.max(0,e.right-e.left),height:Math.max(0,e.bottom-e.top)});u&&f.css("left",e.right-f[0].offsetWidth);r&&f.css("top",e.bottom-f[0].offsetHeight)}).on("mouseup.diagRedim",function(){$(this).off(".diagRedim");$(document.body).css("pointer-events","");f.triggerEvt("redimDone")})}});a?($("header l",f).html(a),$("header b",f).click(function(){_gs(this,!1)}),$("header",f).mousedown(function(c){c.preventDefault();
let m=$(this).closest("dialog");if(!m.is(".maximized")&&!c.target.closest("ctrls")){$(document.body).css("pointer-events","none").parent().css("cursor",$(this).css("cursor"));var p=c.clientX-m[0].offsetLeft,n=c.clientY-m[0].offsetTop,t;$(document).on("mousemove.dialogDrag",function(r){m.css({top:r.clientY-n,left:r.clientX-p});t=!0}).on("mouseup.dialogDrag",function(){$(this).off(".dialogDrag");$(document.body).css("pointer-events","");t&&f.triggerEvt("redimDone")})}})):$("header",f).addClass("hidden");
$("content",f).append(b);f[0].Show=function(c){$(this).addClass("beforePopup1 transformAndOpacityBounceFast");$(this).attr("modal",!!c);this[c?"showModal":"show"]();$(this).triggerEvt("dialogOpen").removeClass("beforePopup1");return this};k&&f.css({width:k[0],height:k[1]});a=_Jw(q)?{left:_fu(q[0],-10,window.innerWidth-(k?k[0]/2:100)),top:_fu(q[1],-10,window.innerHeight-(k?k[1]/2:100))}:_dp(f,"mouse"==q);a:for(;;){for(let c of document.querySelectorAll("dialog"))if(8>Math.abs(c.offsetLeft-a.left)&&
8>Math.abs(c.offsetTop-a.top)){a.left+=15;a.top+=15;continue a}break}return _Gr(f).css(a)[0]}function _Lg(a=!0){a?$("busySign")[0]||_a("busySign",{},_p).addClass("float").appendTo("body"):$("busySign.float").remove()};
