'use strict';let _Rk=_we(function*(){for(let b=0;10>b;++b){var a=speechSynthesis.getVoices();if(!_ul(a))break;yield _za(5)}return a});function _Iy(a,b,c){for(let d of b)a[d]&&a[d].addListener(c)}function _Qs(a,b,c){for(let d of b)a[d]&&a[d].removeListener(c)}
window.addEventListener("error",a=>{var b=a.composedPath&&a.composedPath().map(c=>c.nodeName);b={tgtElem:_ji(a,"target","nodeName"),path:b};a.error&&b.add({error:a.error,stack:a.error.stack,elemSrc:a.error.src});b.stack||b.add({msg:a.message,file:a.filename,line:a.lineno,col:a.colno});_Ot("error",b)},!0);
const _Aw=(a,b,c)=>_Yk.runtime.lastError,_Vt=(a=!1)=>b=>{_Yk.windows.getAll({populate:a,windowTypes:_Ge},c=>b(c.filter(d=>!_9j._Ld[d.id])))},_zg=(a={})=>b=>{_Yk.tabs.query(a,c=>b(c&&c.filter(d=>!_9j._Ld[d.windowId])))},_Ms=(a,b=!1,c)=>_Yk.windows.get(a,{populate:b,windowTypes:_Ge},c),_zh=a=>a&&(a.url||a.pendingUrl)||"about:blank";function _js(a){return a.id==_Yk.tabs.TAB_ID_NONE?-a.windowId:a.id}function _Yw(a={}){return a.focused&&"minimized"!=a.state}
let _Ou=a=>b=>{_Yk.tabs.create({url:a,active:!0},c=>{_Yk.tabs.onUpdated.addListener(function g(f,e){f==c.id&&"complete"==e.status&&(_Yk.tabs.onUpdated.removeListener(g),b(c))})})},_Xu=_we(function*(a){let b=yield c=>_Yk.windows.getLastFocused(c);a.windowId!=b.id&&_Yk.tabs.move(a.id,{windowId:b.id,index:-1});return yield c=>_Yk.tabs.update(a.id,{active:!0},c)}),_Qo=_we(function*(a=""){let b=yield _zg({url:_Yk.runtime.getURL(_ak)});b=b.filter(c=>!_Ko(_zh(c)));return b[0]?yield _Xu(b[0]):yield _Ou(_ak+
"#"+a)}),_0s=_we(function*(){var a=yield _Qo("none");a=_Yk.extension.getViews({tabId:a.id})[0];yield _Xp(a)._Hu.wait();return a}),_0j=_we(function*(){return window==_9j||_Uy?window.frameElement&&!_Xp(window.parent)._Uy?window.parent:yield _0s():window}),_id,_es=/^ /;_Yk.extension.isAllowedFileSchemeAccess(a=>{_id=a;_es=new RegExp(`^(chrome|edge|about:|data:|view-source:|https:\/\/chrome.google.com\/webstore\/${a?"":"|file:"})`,"i")});const _As=a=>_es.test(a);
function _Ah(a){return a.charCodeAt(0)}function _Lj(a){return String.fromCharCode(a)}function _Gt(a,b,c=!0){return RegExp((b.in("equals","starts")?"^":"")+_3a(a)+(b.in("equals","ends")?"$":""),c?"i":"")}function _3a(a){return _Bi(a,"^$\\.*+?()[]{}|")}function _wh(a){return a.split(":")}function _hf(a){return!(!a||!_wh(a)[1])}function _gh(a,b=null){if(!a)return{};const c=_wh(a),d=1<c.length;d&&([b,a]=c);return _ji(d?_9j._if:_9j._Du,b,a)||{}}
function _w(a,b){a=_gh(a,"action").value;a.gener&&(a=a.gener(b));return a}function _1e(a,b,c,d){a=_Ii(a);let f=_wh(a.shift());_Mi(["customEntities"].concat(f,a),b,c,d)}function*_Xy(a,b=!1){const c=_9j._if[a]||{};let d=Object.keys(c).filter(f=>c[f].name&&c[f].value);b&&d.sort((f,e)=>_Vo(c[f].name,c[e].name));for(let f of d)yield a+":"+f}let _7o={};var _Zs=a=>b=>{var c=a.match(/^data:[^;]*;base64,(.+)$/);if(c)return b(c[1]);if(c=_7o[a])return b(c);_1p(a,"binary")(d=>b(_7o[a]=btoa(d)))};
function _Ot(a,b={},c){if(_9j._2u()&&a.in("error","NH-error","NH-except","userReload"))return c&&c();const d=navigator;var f=(d.userAgent.match(/\((.+?)\)/)||[,""])[1].split(/\s*;\s*/);const e=[..._9j._Zw].map(([,g])=>100*g.dpiX/96);f={uri:location.pathname+location.search+location.hash,natHostVer:"2025.4.22.0",brwrLang:d.language,brwrVariant:_ul(_fr)?void 0:_fr,osExtra:f[1]||d.platform,scaleFctr:1==e.length&&100==e[0]?void 0:e};_9j._dh&&(f.connectTime=Date.now()-_9j._dh);_1p(_Zo+"appEvent","json",
"POST",_yp({extName:"AutoCtrl",extVer:"2025.4.22",eventType:a,instID:_9j._7y,timeOffset:Math.floor((Date.now()-_9j._Ct)/1E3),opSys:_Ie?d.platform+" "+_Ie:d.platform.match(/^win/i)?"Windows":d.platform,brwrName:_9j._Jh||_fr[0]||"",brwrVer:_rs,ctxData:JSON.stringify(f),evtData:JSON.stringify(b),domain:location.hostname}))(c)}function _Cr(a,b){null!=b&&_Yk.browserAction.setBadgeBackgroundColor({color:b});null!=a&&_Yk.browserAction.setBadgeText({text:a})}
function _7g(a,b=!1){const c=[94,14,77,49,13];let d=b?new Uint8Array(a.length):"";for(let f=a.length;0<=--f;){let e=a.length-f-1,g=(a.charCodeAt(f)-c[e%c.length]-e)%256;0>g&&(g+=256);b?d[e]=g:d+=String.fromCharCode(g)}return d}
let _3t=_we(function*(a,b){const c="B64"==b,d="blob"==b,f=/\.dat$/.test(a);if(d&&f||c)b="binary";b=yield _1p(a,b);f&&(b=_7g(b,d),/\.gz\./.test(a)&&(b=d?yield _tu(new Blob([b]),"gzip"):yield _Ro(b,"gzip")),!d||b instanceof Blob||(b=new Blob([b])));c?b=btoa(b):b instanceof Blob&&(b=new Blob([b],{type:"application/vnd.microsoft.portable-executable"}));return b});
function _ly(a,b,c=document){"string"==typeof c&&(c=document.querySelector(c));a=c.querySelector("#"+a).innerHTML.trim();b={URLS:_4a,EXT:_Bj}.add(b);return a=a.replace(/\$\{([\w.#]+)\}/g,(d,f)=>"#"==f[0]?_ly(f.substr(1),b,c):_ji(b,...f.split(".")))}let _Xp=a=>a;
var _ve=_cg(function*(a,b){b||(b=yield _ru("toolbarBtns",a));if(_ji(b,"icon","img")){var c=yield _zr(b.icon.img);let d=_Ve(c.width,c.height).getContext("2d");d.drawImage(c,0,0);c=d.getImageData(0,0,c.width,c.height);c={data:[...c.data],width:c.width,height:c.height}}b=(_ji(b,"title")||"").replace(/<br>/g,"\n")+"\v"+Array(+a+2).join("\t");_Yk.runtime.sendMessage(_gj[a],{type:"btnProps",title:b,icon:c})});
{var _Id=function(e,g){try{switch(g){case "UTF-16LE":return f(e,!1);case "UTF-16BE":return f(e,!0);case "UTF-8":case "US-ASCII":return c(e)}}catch(h){}return e},_pk=function(e,g,h=!0){switch(g){case "UTF-16LE":return d(e,!1,h);case "UTF-16BE":return d(e,!0,h);default:try{return btoa(e),e}catch(k){}case "UTF-8":return b(e,h)}};const a=String.fromCharCode(65279),b=function(e,g){e=e.length&&65279!=e.charCodeAt(0)&&g?a+e:e;return unescape(encodeURIComponent(e))},c=function(e){e=decodeURIComponent(escape(e));
return 65279==e.charCodeAt(0)?e.substr(1):e},d=function(e,g=!1,h){e=e.length&&65279!=e.charCodeAt(0)&&h?a+e:e;h=8*+g;g=8*+!g;let k="";for(let l=0;l<e.length;++l){const m=e.charCodeAt(l);k+=String.fromCharCode(m>>h&255);k+=String.fromCharCode(m>>g&255)}return k},f=function(e,g=!1){const h=+g;g=+!g;let k="";for(let l=0;l<e.length;l+=2)k+=String.fromCharCode(e.charCodeAt(l+h)|e.charCodeAt(l+g)<<8);return 65279==k.charCodeAt(0)?k.substr(1):k}}
function _lo(...a){return 1==a.length?_j(a[0]):_9k(a[0],a[1])}function _Ko(a){"string"==typeof a&&(a=new URL(a));a=(a.hash||"").slice(1);return a.startsWith("script=")?a.split("=")[1]:!1}function _3d(a,b){_Mw({trigActList:null,mouseGest:{}},a,c=>{let d=[];for(let [,f]of c.trigActList)f.disabled||d.push(f.triggers);"other"==_ji(c.mouseGest,"triggers","preset")&&d.push(c.mouseGest.triggers);b(!!JSON.stringify(d).match(/"closed":true/))})}
let _Ee=_we(function*(a,b){if(!b){b=yield d=>_9i({trigActList:[]},d);var c=0}for(let [d,f,e]of _Dr(b.trigActList))if("preconds"==d&&f.chromeState&&(f.chromeState.inactive||f.chromeState.closed)){switch(a){case "set":e.author={};case "del":case "add":_lf(e,"author",_9j._7y,"del"==a?void 0:1,NaN);break;case "clear":e.author&&(e.author=void 0)}++c}c&&(yield d=>_bd(b,d));return!!c});
function _Bw(a){if(a.author&&_9j._uy){let b=_ji(a,"preconds","chromeState");return b&&!a.author[_9j._7y]&&(b.inactive||b.closed)}return!1}function _5h(a,b,c,d){d=d||1024;b=b||3;for(var f=0;1E3<=a;++f)a/=d;return(c||"0 1").replace(/(0|1)/g,function(e,g){return[+a.toPrecision(b-(1>a)),f?" KMGTPEZY"[f]:""][g]})}
let _xg=_we(function*(a,b="",c=!1,d="",f=!0){a=(a.match(/\b[a-z]:[^:<>|*?"]+/i)||a.match(/\\\\[a-z][^:<>|*?"]+/i)||a.match(/[^:<>|*?"]+/i)||[""])[0].replace(/\//g,"\\").replace(/(?!^)\\{2,}/g,"\\");"DIR"!=b&&(b=b.replace(/\s*[:,]\s*/g,"\x00")+"\x00");for(var e=!1,g=0;2>g&&!1===e;++g)e=yield _9j._Vy(_e,{path:a,filter:b,dfltExt:d,modal:f,saveAs:c}),a="";return e});const _Cu="chrome://favicon/";function _ig(a){return _Cu+(a.startsWith("data")||a.startsWith("javascript")?"":a)}
function _hw(a){"string"==typeof a&&(a=[{menuId:0,negate:"closed"==a}]);return a}function _po(a,b){a=_Nf(a)?new URL(a):new URL("dummy:"+a);var c=a.pathname.replace(/\/+$/g,"");if(c){if(a=c.match(/[^\/]+$/)[0].replace(/([^.]+\.\w+):.+$/,"$1"),b){c=/\.([^.]+)$/;let d=(a.match(c)||[,""])[1].toLowerCase();d?d[0]!=b[0]&&(a=a.replace(c,"."+b)):a+="."+b}}else a=a.hostname+(b?"."+b:"");return decodeURIComponent(a).replace(/[\/\\:*?"<>|]/g,"_")}
{const a=["userVars"],b=["userVars"];var _ur=(c,d,f=!0)=>(f?b:a).concat(c||"",d?(d+"").split("."):[]),_Rd=c=>null===c||Number.isNaN(c)?void 0:c,_ae=_we(function*(c,d){return yield _ru(..._ur(c,d,!1))}),_ge=(c,d,f,e)=>g=>_Mi(_ur(c,d,e),_Rd(f),0,g),_aa=(c,d)=>f=>_Mi(_ur(c,d,!1),void 0,0,f)};
