'use strict';const _Et={oper:"filter",params:{tgtExpr:"<windowId>",refExpr:"<windowId>"}},_te={oper:"sort",params:{order:"mru",desc:!0}};
_Du.tse={other:{value:[]},currentTab:{name:"Current tab",help:"cur",value:""},prevUsedTab:{name:"Previous tab",help:"prv",value:[_Et,_te,{oper:"filter",params:{pos:"next",wrap:!0}}]},nextUsedTab:{name:"Next tab",help:"nxt",value:[_Et,_te,{oper:"filter",params:{pos:"prev",wrap:!0}}]},prevUsedTabAnyWin:{name:"Previous tab (any win.)",help:"prvAll",value:[_te,{oper:"filter",params:{pos:"next",wrap:!0}}]},nextUsedTabAnyWin:{name:"Next tab (any win.)",help:"nxtAll",value:[_te,{oper:"filter",params:{pos:"prev",
wrap:!0}}]},activeTabs:{name:"Active tabs",help:"act",value:[{oper:"filter",params:{tgtExpr:"<active>",refExpr:"true"}}]},activeTab:{name:"Active tab",help:"act0",value:[{oper:"filter",params:{tgtExpr:"<active>",refExpr:"true"}}]},openerTab:{name:"Opener tab",help:"opnr",value:[{oper:"filter",params:{tgtExpr:"<id>",refExpr:"<openerTabId>"}}]},leftTab:{name:"Left tab",help:"lft",value:[_Et,{oper:"filter",params:{pos:"prev"}}]},leftTabWrap:{name:"Left tab (wrap)",help:"",value:[_Et,{oper:"filter",params:{pos:"prev",
wrap:!0}}]},rightTab:{name:"Right tab",help:"rgt",value:[_Et,{oper:"filter",params:{pos:"next"}}]},rightTabWrap:{name:"Right tab (wrap)",help:"",value:[_Et,{oper:"filter",params:{pos:"next",wrap:!0}}]},firstTab:{name:"Leftmost tab",help:"",value:[_Et,{oper:"slice",params:{from:1,to:1}}]},lastTab:{name:"Rightmost tab",help:"",value:[_Et,{oper:"slice",params:{from:-1,to:-1}}]},newestTab:{name:"Newest tab",help:"nwst",value:[_Et,{oper:"sort",params:{order:"creation"}},{oper:"slice",params:{from:-1,to:-1}}]},
hoveredTabs:{name:"Hovered tab",help:"hvr",value:[{oper:"filter",params:{anyHvrd:!0}}]},allLeftTabs:{name:"All tabs to the left",help:"",multi:1,value:[_Et,{oper:"filter",params:{pos:"before"}}]},allRightTabs:{name:"All tabs to the right",help:"",multi:1,value:[_Et,{oper:"filter",params:{pos:"after"}}]},eventTabs:{name:"Event tab",help:"evt",value:[{oper:"filter",params:{evtTabs:!0}}]},highlighted:{name:"Selected tabs",help:"hlt",multi:1,value:[_Et,{oper:"filter",params:{tgtExpr:"<highlighted>",refExpr:"true"}}]},
pinnedTabs:{name:"Pinned tabs",help:"pin",multi:1,value:[_Et,{oper:"filter",params:{tgtExpr:"<pinned>",refExpr:"true"}}]},audibleTabs:{name:"Audible tabs",help:"aud",multi:1,value:[{oper:"filter",params:{tgtExpr:"<audible>",refExpr:"true"}}]},nonMinimTabs:{name:"Non-minimized tabs",help:"vsbl",multi:1,value:[{oper:"filter",params:{tgtExpr:"<window.state>",refExpr:"minimized",negate:!0}},{oper:"filter",params:{tgtExpr:"<window.state>",refExpr:"hidden",negate:!0}}]},otherTabs:{name:"Other tabs (curr. window)",
help:"othr",multi:1,value:[_Et,{oper:"filter",params:{tgtExpr:"<active>",refExpr:"false"}}]},otherTabsAllWins:{name:"Other tabs (all windows)",help:"othrAll",multi:1,value:[{oper:"filter",params:{tgtExpr:"<id>",refExpr:"<id>",negate:!0}}]},currWinTabs:{name:"All tabs (curr. window)",help:"",multi:1,value:[_Et]},currWinTabsMruOrder:{name:"All tabs (curr. window, MRU order)",help:"curWmru",multi:1,value:[_Et,_te]},allTabs:{name:"All tabs (all windows)",multi:1,value:[]},allTabsMruOrder:{name:"All tabs (all windows, MRU order)",
help:"allMru",multi:1,value:[_te]}};_Du.tse.add({righTab:_Du.tse.rightTab,righTabWrap:_Du.tse.rightTabWrap});
function _My(b){if(!b.ufOper)return b;b.oper=b.ufOper;delete b.ufOper;let a=b.params||{};"string"==typeof a.refTab&&(a.refTab=_ty(_gh(a.refTab,"tse").value));"string"==typeof a.tabSet&&(a.tabSet=_ty(_gh(a.tabSet,"tse").value));if(a.compOper&&a.compOper.in("contains","starts","ends")){let d=("starts"==a.compOper?"^":"")+_Bi(a.refExpr||"","^$\\.*+?()[]{}|")+("ends"==a.compOper?"$":"");a.refExpr={templ:d,regex:!0}}delete a.compOper;a.tgtExpr&&(a.tgtExpr.in("prev","next","before","after")?(a.pos=a.tgtExpr,
delete a.tgtExpr):"openerTabId"==a.tgtExpr?(a.tgtExpr="<openerTabId>",a.refExpr="<id>"):"windowId"==a.tgtExpr?a.tgtExpr=a.refExpr="<windowId>":"groupId"==a.tgtExpr?a.tgtExpr=a.refExpr="<groupId>":"favList"==a.tgtExpr?delete a.tgtExpr:"evtTabs"==a.tgtExpr&&(delete a.tgtExpr,a.evtTabs=!0));"reverse"==a.order&&(b.oper=a.order);return b}const _M=new WeakMap;let _eg=0;
function _zy(b,a=!0){"string"==typeof b&&(b=_gh(b,"tse").value);if(!b)return b;if(a&&_M.has(b))return _M.get(b);const d=b;b=_ty(b);for(let c of b)_My(c),"filter"==c.oper?(c.params.tgtExpr=_Tt(c.params.tgtExpr),c.params.refExpr=_Tt(c.params.refExpr),c.params.refTab=_zy(c.params.refTab,!1)):"sort"==c.oper?c.params.order=_Tt(c.params.order):"addSet"==c.oper?(++_eg,c.params.tabSet=20<_eg?[]:_zy(c.params.tabSet,!1),--_eg):"groupBy"==c.oper&&(c.params.expr=_Tt(c.params.expr));a&&_M.set(d,b);return b}
function _gt(b,a){return _ou(_zy(b),a)}function _ou(b,a){if(!b)return _Np?[[_Np]]:[[]];a=a?a.slice():[_Gk];a[0]||(a[0]=[]);for(let d of b)d.oper&&(a=_kj(a,d.oper,d.params),a[0]||(a[0]=[]));return a}function _qd(b){return[...new Set(_Ii(...b))]}function _Vp(b,a,d){a=Math.max(1,(a||1)+(0>a?b.length+1:0))-1;d=Math.max(a,(d||b.length)+(0>d?b.length+1:0));return b.slice(a,d)}
function _kj(b,a,d){if("mergeGrp"==a)return[_qd(b)];if("addSet"==a){var c=_ou(d.tabSet);return d.replace?c:b.concat(c)}if("slice"==a&&d.groupWise)return _Vp(b,d.from,d.to);if("reverse"==a&&d.groupWise)return b.slice().reverse();c=[];a=_pp[a];for(let e of b)c.push(...e.length?a(e,d):[]);return c}const _pp={filter:_Mg,posFilter:_Mg,sort:_qf,groupBy:_Nj,reverse:b=>[b.slice().reverse()],slice:(b,a)=>[_Vp(b,a.from,a.to)]};
function _qf(b,a){let d=a.order;a=a.desc;switch(d){case "normal":b=_hg(b,_Gk);break;case "mru":b=_hg(b,_Ft,!0);break;case "zOrder":b=_Sd(b);break;case "creation":b=_hg(b,_ea,!0);break;default:let c={};for(let e of b)c[e]=_wy(d,_Yp[e]);b=b.slice().sort((e,f)=>{e=c[e];f=c[f];return e==f?0:e<f?-1:1})}a&&b.reverse();return[b]}
function _Sd(b){if(_ko)return _Lw.addFunc(_us(function*(){_ko&&(yield _Vy(_Yj),_ko=!1)})),b.slice();let a=0;for(let d of _ts)_cd[d].zIndex=a--;_Ft=_hg(_Gk,_Ft,!0);for(let d of b)_Yp[d].mruIndex=_Ft.indexOf(d);return b.slice().sort((d,c)=>{let e=_Yp[d].window.zIndex-_Yp[c].window.zIndex;return e?e:_Yp[d].mruIndex-_Yp[c].mruIndex})}
function _Nj(b,a){let d=_la();for(let c of b){if("overlapArea"==a.expr){let e=_df(_Yp[c].window);b=0;for(let [,f]of d){let h=_df(_Yp[f[0]].window);if(_Zg(_il(e),h)||_Zg(_il(h),e))break;++b}}else b=_wy(a.expr,_Yp[c]);d[b]||(d[b]=[]);d[b].push(c)}return[...d].map(([,c])=>c)}let _hu;function _st(){if(_hu)return _hu;_Lw.addFunc(_us(function*(){_hu=yield _Vy(_3f,{usePrvMsPos:!!_Cg(_zw).usePrevMousePos})}));return{}}
function _3u(b=!1,a=!1,d=!1){const c={TSE:g=>_Ii(..._gt(g)),tabList:g=>g,tab:g=>[g]};let e=[],f=g=>{(g=_Tu(g))&&g.type in c&&e.push(...c[g.type](g.content))},h=_st();b&&h.marked&&f(h.marked);a&&h.hilited&&f(h.hilited);d&&h.hovered&&f(h.hovered);return[...new Set(e)].filter(g=>g in _Yp)}
function _Mg(b,a){let d=[],c;if(a.favList)c=_Mo[a.favList]||[];else if(a.evtTabs)c=_Eh(_zw);else if("menuSeltn"==a.tgtExpr)c=_3u(a.marked,a.hilited,a.hovered);else if(a.anyHvrd)c=_3u(!1,!1,!0),c.length||(c=_ys(),c.length||(c=[_ji(_cd,_Jg(),"activeTab","id")]));else if("grpSize"==a.tgtExpr)return a.min<=b.length&&b.length<=a.max?[b]:[];if(c)d=b.filter(f=>0<=c.indexOf(f)==!a.negate);else{var e=_Yp[a.refTab?_ou(a.refTab,[b])[0][0]:_Np];if(e)if(a.pos)d=_xy(b,a,e.id),a.negate&&(d=b.filter(f=>-1==d.indexOf(f)));
else{e=_wy(a.refExpr,e);for(let f of b)b=_wy(a.tgtExpr,_Yp[f]),(b instanceof RegExp?b.test(e):e instanceof RegExp?e.test(b):String(b)==String(e))==!a.negate&&d.push(f)}}return[d]}function _xy(b,a,d){var c=b.indexOf(d);if(0>c)return[];b=[b.slice(0,c),b.slice(c+1).reverse()];c=a.pos.in("before","prev");let e=b[+!c].reverse();a.addRef&&e.unshift(d);a.wrap&&(e=e.concat(b[+c]));a.pos.in("prev","next")&&(e=e.slice(0,1));return e};
