'use strict';var _Uy=(t=>null==t?null:{filePath:t})(_yi().file);let _Ho=!0;
if(_Uy){let t=function(a,b,c,e){function l(...k){return new Proxy(()=>{},{get(f,g){f=[...k,g];var h=f.join(".");h=h in e?e[h]:b;if("function"===typeof h)return h(_ji(a,...f));if(h)return l(...k,g);g=_ji(a,...f);1<f.length&&"function"==typeof g&&(g=g.bind(_ji(a,...f.slice(0,-1))));return g},set(f,g,h){[...k]},apply(f,g,h){}})}return l()},m={},u={},p,q,n,y=_we(function*(){u=(yield _ru("customEntities"))||{}}),w=_we(function*(a){m=a;yield y();n&&_Ho&&n.toggleClass("noContent",_ul(m))}),z=_we(function*(a){let [b,
c]=yield _mg(_1p(a,"text","GET",void 0,{"Cache-Control":"no-cache, no-store, max-age=0"}));return 200==c.status?{content:b}:{error:_wu(c.status,c)}}),A=_we(function*(a){a=yield _9j._If(a,"text");a.error&&(a.error=yield _9j._Vy(_xo,+a.error));return a});_Uy.filePath&&(p=_we(function*(){p=null;let a=_1(_Uy.filePath)?yield A(_Uy.filePath):yield z(_Uy.filePath);if(a.error)q=a.error;else if(_Uy.fileEncode=a.charEnc,a.content)try{yield w(JSON.parse(a.content))}catch(b){q="The format of the specified file is invalid."}}));
let B=a=>b=>{chrome.storage.local.set({["__dummy__"]:a},()=>{chrome.storage.local.get("__dummy__",c=>{chrome.storage.local.remove("__dummy__");b(c.__dummy__)})})},C=_Es(400,()=>{n.addClass("unsaved").toggleClass("noContent",_ul(m));_rg()()});_Nh=function(a){return t(a,!0,"CHROME",{tabs:null,windows:null,"runtime.id":null,"runtime.getManifest":null,"runtime.getURL":null,"runtime.lastError":()=>null,"extension.getViews":null,"extension.isAllowedFileSchemeAccess":null,"extension.isAllowedIncognitoAccess":null,
bookmarks:null,"storage.sync.QUOTA_BYTES":null,"storage.sync.getBytesInUse":null,"storage.local.get":()=>(b,c)=>{let e=()=>c(_ty({}.add(b,b?m.sc().keep(Object.keys(b)):m)));p?p()(e):setTimeout(e,0)},"storage.local.set":()=>(b,c)=>{let e=()=>{B(b)(l=>{m.add(l);n&&_Ho&&C();c&&c()})};p?p()(e):e()},"permissions.getAll":()=>b=>setTimeout(()=>b({permissions:["bookmarks","sessions","background","notifications","downloads"],origins:["<all_urls>"]}),0),"runtime.sendMessage":()=>(b,c,e)=>{e&&("ping"==c?_9i({toolbarBtns:{}},
l=>{(_gj.indexOf(b)+"").in(Object.keys(l.toolbarBtns))?e("pong"):e()}):e())},"extension.getBackgroundPage":b=>()=>t(b(),!1,"BP",{"":"",_if:()=>u,_ps:()=>({}),_uy:()=>!1,_nk:!0,_ku:!0,_Gf:!0,_no:!0,_zj:!0,_8a:!0,_Jf:!0,_6t:!0,_Jp:!0,_6s:!0," ":""})})};let x=_we(function*(a,b){_Ho=!1;const c=yield f=>_9i({trigActList:[],toolbarBtns:{},sections:[]},f);let e={},l=[];"new"==b&&(b=_o(),c.sections.push({id:b,name:"Imported actions"}),e[b]=!0);for(let f of Object.keys(c.trigActList)){var k=c.trigActList[f];
if(~a.indexOf(f)){void 0===b?e[k.sctnId]=!0:k.sctnId=b;for(let [g,h]of _Dr(k.triggers))"eventId"==g&&(k=_eh(h),k.type==_cf&&_rj(k.num)&&l.push(k.num-_At))}else delete c.trigActList[f]}yield f=>_bd({trigActList:c.trigActList,sections:c.sections.filter(g=>e[g.id]),toolbarBtns:c.toolbarBtns.keep(l)},f);yield _me();m.del("mouseGest","advOpts","userVars","joysticksOrder","previewMakerParams","scrtEdtr");_Ts(m);_Ho=!0});_Uy.afterLoad=_we(function*(){function a(){let d=q||!_Uy.filePath?"New file":_Uy.filePath.replace(/^.*[\/\\]/,
"");document.title=d+" - Settings File Editor";$(window.frameElement).triggerEvt("titleChange")}let b=!1,c=()=>_1(_Uy.filePath)?_Uy.filePath.replace(/[^\\]+\.[^\\]+$/,""):"";const e=_we(function*(d,r=m){if(!_Uy.filePath||q||d){d=yield _xg(_ul(r)?c():!_Uy.filePath||_1(_Uy.filePath)?_Uy.filePath:_po(_Uy.filePath),_to,!0,_Lu);if(!d)return!1;history.replaceState(null,"",location.pathname+"?file="+encodeURIComponent(d)+location.hash);_Uy.filePath=d;q=null;n.find("> [type=text]").val(d);a()}let v;_1(_Uy.filePath)?
(r=yield _9j._4u(_Uy.filePath,_pk(JSON.stringify(r),"UTF-8",!1)))&&(v=`Error while saving to the file. <hr b=2> "${_Uy.filePath}" <hr b=2> ${yield _9j._Vy(_xo,+r)}`):v='Changes cannot be saved to an internet address. <hr b> Click on "Save as" in order to save to a local file.';if(v)return _Xp(!b&&window.frameElement?window.parent:window)._u(v,{type:"error"}),!1;n.removeClass("unsaved");return!0});let l=_Uy.safeToClose=d=>{n.is(".unsaved")?_Ng("","Unsaved changes will be lost if you continue. <hr b=2> Discard changes?")(d):
d(!0)},k,f=d=>{k=!0;location.replace(d)};$(window).on("beforeunload",d=>{if(!k&&n.is(".unsaved"))return"Discard changes?"});window.frameElement&&$(window).captureTgtEvt("mousedown",()=>$(window.frameElement).triggerEvt("mousedown",!0));p&&(yield p());a();yield d=>_4h("file40.css",d);n=$(`\n <fileEditBar helpCtx=sttgFilEdt>\n <img src="/AutoCtrl/logo32.png" width=26>\n <h h=welcm sides=br></h>\n <l>Settings file:</l>\n ${_oo("",q?"":_Uy.filePath,"No file path specified","readonly")}\n <!--btn act=new>New file</btn><h h=new></h-->\n <btn act=open>Open</btn><h h=opn sides=brl></h>\n <btn act=save>Save</btn><h h=sav sides=brl></h>\n <btn act=savAs>Save as</btn><h h=savAs sides=brl></h>\n <btn act=dscrd>Discard</btn><h h=disrd sides=brl></h>\n <btn act=impAll>Import all</btn><h h=imAll sides=brl bublCls=sharpCorner></h>\n </fileEditBar>\n `).on("click",
"btn",_cg(function*(d){d=$(this).attr("act");if(!d.in("new","open","dscrd")||(yield l))switch(d){case "new":(yield e(!0,{}))&&f(location.pathname+location.search);break;case "open":(d=yield _xg(c(),_to))&&f(location.pathname+"?file="+encodeURIComponent(d));break;case "savAs":case "save":yield e("savAs"==d);break;case "dscrd":f("?file="+encodeURIComponent(_Uy.filePath));break;case "impAll":(yield _Ng("","This will add the entire content of this settings file <br> to your AutoControl settings. <hr b=2> Continue?"))&&
_uw(yield r=>_9i(_2d,r))}})).appendTo(document.body);$(document.body).addClass("SFE_mode");let g=!0;var h=!0;if(null!=_yi().storInit){let [d,r]=window.frameElement.storInit;yield w(d);yield x(r);g=yield e(!0);h=`The actions have been successfully saved to: <hr b=2> "${_Uy.filePath}" <hr b=2> Do you want to review the file.`;h=g&&(yield _Xp(window.parent)._Ng("",h,{icon:"success"}))}else _Uy.filePath||(yield w({}));$("body > tabs").append("<perms><tit>Permissions <h h=prmLst></h></tit><cont></cont></perms>");
$(window.frameElement).triggerEvt({contentReady:h});q&&setTimeout(()=>_u(`Error while opening the file. <hr b=2> "${_Uy.filePath}" <hr b=2> ${q}`,{type:"error"}),300);_Jk("SFE_welcmShown",!0)||_Li(_Wp.wait(),_za(50))(()=>$("[h=welcm]",n).triggerEvt({mousedown:!0}));b=!0;return g});let D=_we(function*(a,b){const [c,e]=[_ty(m),_ty(u)];yield x(a,b);a=yield l=>_9i(_2d,l);[m,u]=[c,e];return a});var _dj=_cg(function*(a,b){a=a.get().map(c=>$(c).attr("actionId"));a=yield D(a,b);_uw(a,"new"!=b,!0,!0,!1,!1)})};
