'use strict';const _ay=()=>{};Object.freeze(_ay);
Object.defineProperties(Object.prototype,{"in":{writable:!0,value:function(...a){return _Xt(this,...a)}},includes:{writable:!0,value:function(a){for(let b in a)if(this[b]!=a[b])return!1;return!0}},add:{writable:!0,value:function(...a){for(let b of a)if(b)for(let [c,d]of b)this[c]=d;return this}},del:{writable:!0,value:function(...a){for(let b of _Ii(...a))delete this[b];return this}},keep:{writable:!0,value:function(...a){a=_Ii(...a).map(b=>String(b));for(let b in this)b.in(a)||delete this[b];return this}},
sc:{writable:!0,value:function(){let a={};for(let b in this)a[b]=this[b];return a}},[Symbol.iterator]:{writable:!0,value:function*(){for(let a in this)this.hasOwnProperty(a)&&(yield[a,this[a]])}}});NodeList.prototype.hasOwnProperty(Symbol.iterator)||Object.defineProperty(NodeList.prototype,Symbol.iterator,{writable:!0,value:[][Symbol.iterator]});HTMLCollection.prototype.hasOwnProperty(Symbol.iterator)||Object.defineProperty(HTMLCollection.prototype,Symbol.iterator,{writable:!0,value:[][Symbol.iterator]});
Object.defineProperties(Array.prototype,{add:{writable:!0,value:function(a){-1==this.indexOf(a)&&this.push(a)}},remove:{writable:!0,value:function(a,b){a=b||"object"!=typeof a||a instanceof Node?this.indexOf(a):_ki(this,a);return-1<a?this.splice(a,1)[0]:void 0}}});const _Kf=(a,b)=>a.filter(c=>0>b.indexOf(c)),_Vw=(...a)=>a.reduce((b,c)=>b.filter(d=>0<=c.indexOf(d)));Object.defineProperty(Set.prototype,"append",{writable:!0,value:function(...a){for(let b of a)this.add(b);return this}});
Object.defineProperties(String.prototype,{caplze:{writable:!0,value:function(){return this&&this[0].toUpperCase()+this.slice(1)}}});function _Ps(a){return a.split("").reverse().join("")}function _Ii(...a){return[].concat(...a)}function _Jw(a){return Array.isArray(a)}function*_Fg(a){_Jw(a)?yield*a.entries():a&&"object"==typeof a&&(yield*a)}function*_va(a){if(_Jw(a))for(let b=a.length-1;0<=b;--b)yield[b,a[b]];else a&&"object"==typeof a&&(yield*a)}
function*_Dr(a){for(let [b,c]of _Fg(a))yield[b,c,a],yield*_Dr(c)}function _Oo(a){for(let [,b]of _Fg(a))"object"==typeof b&&_Oo(b);return Object.freeze(a)}function _Xt(a,...b){for(let c of _Ii(...b))if(a===c)return!0;return!1}function _ki(a,b){for(var c=0;c<a.length;++c)if(a[c].includes(b))return c;return-1}let _Vo=(new Intl.Collator(navigator.language,{sensitivity:"accent",caseFirst:"false",numeric:!0})).compare,_Ha=a=>(null==a?"":a+"").trim().replace(/\s+/g," ");
function _ty(a){return a?JSON.parse(JSON.stringify(a)):a}function _sf(a){if(null==a||"object"!=typeof a)return a;let b=a.constructor.name.in("Boolean","Number","String","Date","RegExp")?new a.constructor(a.valueOf()):new a.constructor;for(var c in a)a.hasOwnProperty(c)&&(b[c]=_sf(a[c]));return b}
function _lf(a,...b){for(let c=0;c<b.length;++c){let d=b[c],e=b[c+1];"object"==typeof d||Number.isNaN(d)||Number.isNaN(e)||(a[d]=Number.isNaN(b[c+2])?e:a[d]||("object"==typeof e?e:"number"==typeof e?[]:{}),void 0===a[d]&&delete a[d],a=a[d])}return a}function _ji(a,...b){for(let c of b){if(!a)break;a=Number.isInteger(c)&&0>c&&_Jw(a)?a[a.length+c]:a[c]}return a}function _eo(a,...b){if(b.length&&"object"==typeof a){let c=b.shift();_eo(a[c],...b)&&(_Jw(a)?a.splice(c,1):delete a[c])}return _ul(a)}
function _ul(a){return null==a||(void 0!==a.length?!a.length:"object"==typeof a&&!Object.keys(a).length)}function _qw(a){return Math.round(+a)}function _fu(a,b,c){return Math.max(b,Math.min(a,Math.max(b,c)))}function _yd(a,b=0){b=Math.pow(10,b);return Math.round(a*b)/b}function _Bi(a,b,c="\\"){return a.replace(/./g,d=>b.includes(d)?c+d:d)}function _jf(a,b="nrt'\"\\"){b=RegExp(_Bi("\\(["+b+"])","\\"),"g");return a.replace(b,(c,d)=>({n:"\n",r:"\r",t:"\t"})[d]||d)}
function _9d(a){const b={'"':"&quot;","'":"&#39;","<":"&lt;",">":"&gt;"};return a.replace(/["'<>]/g,c=>b[c])}function _Uu(a){if(a instanceof DocumentFragment)return a;let b=document.createElement("template");b.innerHTML=a;return b.content}const _mg=a=>b=>a((...c)=>b(c)),_ti=(...a)=>_us(...a)(),_we=a=>function(...b){return _us(a,b,this)},_cg=a=>function(...b){return _us(a,b,this)()};
{let a=null,b=function(d){d.isDone=!0;for(a=d.parentGener;a&&a.isDone;)a=a.parentGener},c=function(d,e,h="next"){try{d.running=!0;var f=d[h](e);d.running=!1}catch(g){b(d);if(d.onError)return d.onError(g);if(a&&!a.running)return c(a,g,"throw");throw g;}if(f.done)return b(d),d.onSuccess?d.onSuccess(f.value):f.value;try{(f.value.then||f.value).call(f.value,g=>{c(d,g)},g=>c(d,g,"throw"))}catch(g){c(d,g,"throw")}};var _us=(d,e,h)=>{d=d.apply(h,e);d.parentGener=a;a=d;return(f,g)=>{d.onSuccess=f;d.onError=
g;return c(d)}}}function _5j(a){return(...b)=>(c,d)=>Promise[a]([].concat(...b).map(e=>"function"==typeof e?new Promise(e):e)).then(c,d)}let _Li=_5j("all"),_Yd=_5j("race"),_4y=(...a)=>b=>{let c=[],d=h=>c.push(h)&&d,e=(...h)=>{var f;if(f=c[0])h=c.shift()(...h),f="function"==typeof h?h(e):h;return f};_Li(...a)(e);return d(b)};function _wk(a){this.readyCount=this.asyncTotal=0;this.args=[];this.callback=a}
_wk.prototype={setCallback(a,b){this.callback=a;this.onReady()();b&&setTimeout(()=>this.callCallback(),b)},callCallback(){this.callback&&(this.callback(..._Ii(...this.args)),delete this.callback)},onReady(a){let b=this.asyncTotal++;return(...c)=>{a&&a(...c);this.args[b]=c;this.asyncTotal==++this.readyCount&&this.callCallback()}}};function _za(a){return b=>setTimeout(b,a)}
function _la(a){if(!new.target)return new Proxy(new _la(a),{get(b,c){return"length"==c?b.order.length:"function"==typeof b[c]?b[c].bind(b):b.dict[c]},set(b,c,d){b.set(c,d);return!0},deleteProperty(b,c){b.del(c);return!0},has(b,c){return b.has(c)},ownKeys(b){return b.order.slice()},getOwnPropertyDescriptor(b,c){if(b.has(c))return{configurable:!0,enumerable:!0,writable:!0}}});a||(a=[]);this.dict={};this.order=[];for(let [b,c]of a)this.dict[b]=c,this.order.push(""+b)}
_la.prototype={getPos(a){return this.order.indexOf(a)},set(a,b,c=-1){a+="";if(void 0===b)return this.del(a);this.dict.hasOwnProperty(a)||this.order.splice(0>c?this.order.length+1+c:c,0,a);return this.dict[a]=b},add(a){if(a)for(let [b,c]of a)this.set(b,c);return this},setPos(a,b){let c=this.order.indexOf(a);if(0>c)return!1;this.order.splice(c,1);this.order.splice(b,0,a);return!0},del(...a){for(let b of _Ii(...a))delete this.dict[b],this.order.remove(b);return this},delPos(a){this.del(this.order[0>
a?this.order.length+1+a:a])},has(a){return this.dict.hasOwnProperty(a)},[Symbol.iterator]:function*(){for(var a of this.order)yield[a,this.dict[a]]},toJSON(){return[...this]}};function _Nf(a){try{return!!new URL(a)}catch(b){return!1}}function _Xd(a){try{let b=new URL(a);return b.hostname?!0:0<="about bitcoin blob callto data file gtalk magnet mailto maps news skype sms tel urn view-source".split(" ").indexOf(b.protocol.slice(0,-1))}catch(b){return!1}}
function _1(a){try{return"file:"==(new URL(a)).protocol}catch(b){return!1}}function _5w(a){if(_Nf(a))return a;a="http://"+(a||"").trim();return _Nf(a)?a:"about:"}
function _1p(a,b,c="GET",d,e={},h){return(f,g)=>{let k=new XMLHttpRequest,l=m=>{f&&("HEAD"==c?f(k):f(m,k))};const p=b.in("dataUri","binary");k.open(c,a);k.responseType=p?"blob":b;const q=a.startsWith("data:")&&"blob"==k.responseType;q&&(k.responseType="arraybuffer");k.onload=function(){let m=q?new Blob([this.response]):this.response;if(!p)return l(m);let n=new FileReader;n.onload=function(){l(this.result)};n["readAs"+{dataUri:"DataURL",binary:"BinaryString"}[b]](m)};k.onerror=k.onabort=()=>g?g(Error(`Failed to load url '${a}' via ${c}`)):
l(void 0);for(let [m,n]of e)k.setRequestHeader(m,n);k.onprogress=h;k.send(d)}}function _wu(a,b){const c={401:"Unauthorized",403:"Forbidden",404:"Not Found",500:"Internal Server Error"};return a?c[a]?a+" "+c[a]:3<_ji(b,"statusText","length")?b.statusText:"Error "+a:"Unreachable URL"}function _ij(a,b){_1p(a,"blob")(c=>b(URL.createObjectURL(c)))}function _yp(a){let b=new FormData;for(let [c,d]of a)b.append(c,d);return b}
function _xu(a){try{var b=new URL(a)}catch(c){return a}b.hash?b.hash="":b.search?b.search="":1<b.pathname.length?b.pathname=b.pathname.replace(/[^\/:]+\/?$/,""):b.hostname.match(/\.[a-z]/i)&&(b.hostname=b.hostname.replace(/^[^\.]+\./,""));return b.href}function _yi(){return{}.add(new URLSearchParams(location.search.slice(1)))}
function _Es(a,b,c){const d=Math.abs(a),e=0<a;let h=0,f;return function(...g){clearTimeout(f);var k=Date.now()-h;if(k<d){if(e&&(f=setTimeout(()=>{b.apply(this,g);h=Date.now()},d-k)),c)return c.apply(this,g)}else if(k=b.apply(this,g),!Number.isNaN(k))return h=Date.now(),k}}function _so(a,b,c){const d=Math.abs(a),e=0>a;let h=0,f=function(...g){clearTimeout(f.timer);let k=d,l=Date.now();e&&h>l?k=h-l:h=l+k;f.timer=setTimeout(()=>{b.apply(this,g);h=0},k);if(c)return c.apply(this,g)};return f}
function _Wf(a,b){let c=a,d=b,e=[],h=function(){for(;e.length&&void 0!==c;){const [f,g]=e.shift(),k=c;d===f&&(c=void 0);Promise.resolve().then(()=>g(k))}};this.send=function(f=!0,g=0){c=f;d=g;h()};this.wait=function(f=0){return g=>{e.push([f,g]);h()}};this.clear=()=>c=void 0}function _Oh(a){let b=0;return function(...c){if(!b++)return a.apply(this,c)}}
function _sr(a,b,c){let d=document.createElement("SCRIPT");d.isLoaded=!1;d.onload=function(){this.isLoaded=!0;b&&b()};c&&(d.onerror=function(){c(Error(`Failed to load script file "${this.src}"`))});d.src=a;return d}function _9w(a,b){document.head.appendChild(_sr(a,b))}function _ka(a){return(b=_ay)=>{let c=document.querySelector(`script[src='${a}']`);c?null==c.isLoaded||c.isLoaded?b():c.addEventListener("load",b):_9w(a,b)}}let _vs=a=>b=>{window._=void 0;_9w(a,()=>{b(window._);window._=void 0})};
{let a=c=>1==(c+"").length?"0"+c:c,b={Y:c=>c.getFullYear(),y:c=>c.getYear(),M:c=>a(c.getMonth()+1),m:c=>c.getMonth()+1,D:c=>a(c.getDate()),d:c=>c.getDate(),H:c=>a(c.getHours()),h:c=>c.getHours(),I:c=>a(c.getMinutes()),i:c=>c.getMinutes(),S:c=>a(c.getSeconds()),s:c=>c.getSeconds()};var _8h=(c,d="Y-M-D")=>d.replace(/[dDmMyYhHiIsSTw]/g,e=>(b[e]||(()=>e))(c))}
function _Ns(a,b){let c=new Uint8Array(a.length);for(let d=0;d<a.length;++d){let e=a.charCodeAt(d);if(255<e)throw"Charcode above 255";c[d]=e}return new Blob([c],{type:b})}
let _Sr=a=>{try{return _Ns(a)}catch(b){return new Blob([a])}},_Xw=a=>b=>{let c=new FileReader;c.onload=function(){b(this.result)};c.readAsBinaryString(a)},_0u=_we(function*(a,b="deflate"){try{let c=a.stream().pipeThrough(new CompressionStream(b));return yield(new Response(c)).blob()}catch(c){}return a}),_tu=_we(function*(a,b="deflate"){try{let c=a.stream().pipeThrough(new DecompressionStream(b));return yield(new Response(c)).blob()}catch(c){}return a}),_J=_we(function*(a,b="deflate"){return yield _Xw(yield _0u(_Sr(a),
b))}),_Ro=_we(function*(a,b="deflate"){return yield _Xw(yield _tu(_Sr(a),b))});function _j(a){return JSON.parse(localStorage&&localStorage.getItem(a))}function _nt(a){let b=_j(a);localStorage.removeItem(a);return b}function _Jk(a,b){let c=_j(a);c!==b&&_9k(a,b);return c}
function _9k(a,b){let c=JSON.stringify(b);if(c)try{localStorage.setItem(a,c)}catch(d){DOMException&&d.code==DOMException.QUOTA_EXCEEDED_ERR&&(localStorage.clear(),localStorage.setItem(a,c))}else localStorage.removeItem(a);return b}
let _zf=_we(function*(a){for(let b;b=document.querySelector("import[src]"+(a?"":":not([defer])"));){let c=b.getAttribute("src");b.removeAttribute("src");if(c.match(/\.js$/i))yield(d,e)=>b.parentElement.replaceChild(_sr(c,d,e),b);else if(c.match(/\.html$/i))for(let d=0;5>d;++d){try{b.innerHTML=yield _1p(c,"text");break}catch(e){}yield _za(200)}}});var _Hu=new _Wf;document.addEventListener("DOMContentLoaded",()=>_zf(!1)(()=>_Hu.send("",!0)));let _Nh=a=>a;
