'use strict';let _Mh=_cg(function*(a,f,b,d){if(!b.url&&!b.bookmarkId)return f(a);let c=[],e=[],g=!1;if(b.bookmarkId&&_Yk.bookmarks){var h=yield m=>_Yk.bookmarks.getSubTree(""+b.bookmarkId,m);if(!_Aw()&&h.length)if(h[0].url)e=[h[0].url];else{g=!0;for(var k of h[0].children)k.url&&e.push(k.url)}}(h=b.refTab)&&"number"!=typeof h&&(h=(yield _ai(d,_gt,h))[0][0]);h=_Yp[h]||_Yp[_Np];h||(b=b.sc().add({tabPos:"newWin"}),h={});let n=h.windowId;a=_qd(a);a=b.tabPos&&!b.usesTabs?[]:a;let q=(h.index||0)+("after"==
b.tabPos?1:0);a.length||(a=[void 0]);for(h=0;h<a.length;){k=h;b.bookmarkId||(e=_Jw(b.url)?b.url:yield _ai(d,_up,_Tt(b.url||"chrome://newtab"),_Yp[a[h]]));for(let m of e)if(m=m.trim().match(/^.*/)[0].trim(),_Nf(m)){_kk=Date.now();if("newWin"==b.tabPos)if(0==h||"popup"==b.winType){var l=yield p=>_3g({url:m,focused:!1,incognito:b.incognito,type:b.winType},p);!_Aw()&&l&&(n=l.id,c.push(l.tabs[0].id))}else(l=yield p=>_6a({url:m,active:!1,windowId:n},p))&&c.push(l.id);else if(b.tabPos)(l=yield p=>_6a({url:m,
active:!1,windowId:n,index:q++},p))&&c.push(l.id);else if(l=a[h],0<l)m.startsWith("javascript:")?_wj(l,{code:m.slice(11)})():_Yk.tabs.update(l,{url:m}),c.push(l);else if(b.newTabs){let p=_ji(_Yp[a[a.length-1]||_Np],"windowId");(l=yield r=>_6a({url:m,active:!1,windowId:p},r))&&c.push(l.id)}++h}if(g||1<e.length&&1<a.length)break;h==k&&++h}f([c])});
function _c(a){return[{sequence:[{action:"loadUrls",params:{url:"blank"==a.page?"about:blank":"chrome://newtab",tabPos:"after",refTab:"lastTab"}},{action:"activateTabs"}]}]}function _Xs(a,f,b){let d=new _wk;for(let c of _qd(a))0<c&&_Yk.tabs.reload(c,{bypassCache:!!b.force},d.onReady());d.setCallback(()=>f(a))}function _pu(a){return _Yp[a].active&&_Yw(_Yp[a].window)}
function _Ik(a,f,b,d,c){let e=new _wk;for(let g of _qd(d))if(0<g)if(_Yk.tabs[a])_Yk.tabs[a](g,e.onReady());else _pu(g)?_Lk(_Dt,b,e.onReady()):_wj(g,{code:f})(e.onReady());e.setCallback(()=>c(d))}function _Is(a,f){_Ik("goBack","history.back()",[_St,_Mk,_Mk|_mk,_St|_mk],a,f)}function _Zi(a,f){_Ik("goForward","history.forward()",[_St,_4w,_4w|_mk,_St|_mk],a,f)}
function _1r(a,f){let b=new _wk;for(let d of _qd(a)){if(!(0<d))continue;let c=_Yp[d],e=_xu(c.url);e!=c.url&&_Yk.tabs.update(d,{url:e},b.onReady())}b.setCallback(()=>f(a))}
function _Zj(a,f,b={}){let d=new _wk;var c={};for(let e of _qd(a))_Yp[e]&&_lf(c,_Yp[e].windowId,[]).push(e);a=Object.keys(_cd);for(let [e,g]of c)c=_cd[e],c.tabs.length==g.length?"devtools"!=c.type&&(("lastWin"==b.keepWin?1==a.length:b.keepWin)&&"normal"==c.type?(_6a({url:"about:blank",active:!1,windowId:+e},d.onReady()),_Yk.tabs.remove(g,d.onReady())):(_Yk.windows.remove(+e,d.onReady()),a.remove(e))):((c=_qk(e,g,b.switchTo))&&_Yk.tabs.update(c,{active:!0}),_Yk.tabs.remove(g,d.onReady()));d.setCallback(_cg(function*(...e){f([e.filter(g=>
g).map(g=>g.id)])}),1E3)}
function _qk(a,f,b){const [d]=f.filter(c=>_Yp[c].active);if(d&&b){a=_cd[a].tabs.map(e=>e.id);const c=_Kf(a,f);if(1<c.length){const e=a.indexOf(d);switch(b){case "prevUsedTab":return _hg(c,_Ft,!0).slice(-1)[0];case "openerTab":return _Vw(_9a(d),c)[0];case "leftTab":return _Kf(a.slice(0,e),f).slice(-1)[0]||_Kf(a.slice(e+1),f)[0];case "rightTab":return _Kf(a.slice(e+1),f)[0]||_Kf(a.slice(0,e),f).slice(-1)[0];case "firstTab":return c[0];case "lastTab":return c[c.length-1]}}}}
function _9a(a){let f=[];for(;a=_gg(_Yp[a],"openerTabId");)f.push(a);return f}function _Vk(a){return[{sequence:[{action:"closeTabs",params:a}],targets:"currentTab"}]}
function*_Za(a,f,b,d){const c={[_Ap]:"href",[_Io]:"hostname",[_Vr]:"pathname"};let e=h=>!b||b.regex.test((new URL(h.url))[c[b.part]])==!b.negate,g=_ji(_Yp,_Np,"windowId");for(let h of a)h.window?"tab"==f?yield*_Za(h.window.tabs,f,b,d):h.window.tabs.some(e)&&(yield h.window.sessionId):f&&"tab"!=f||(a=h.tab||h,e(a)&&(!d||g&&g==_x[a.sessionId])&&(yield a.sessionId))}
let _3j=_cg(function*(a,f,b,d){let c;if(a=(b.urlTest||{}).value)d=yield _ai(d,_wy,_Tt(a),_Yp[_Np]),c=b.urlTest.sc().add({part:_Io,value:d,regex:_Gt(d,b.urlTest.type)});d=0;a=[];let e=b.maxObjs||1;if(_Yk.sessions){var g=yield h=>_Yk.sessions.getRecentlyClosed(b.objType||c||b.currWinTabs?{}:{maxResults:Math.min(e,_Yk.sessions.MAX_SESSION_RESULTS)},h);for(let h of _Za(g,b.objType,c,b.currWinTabs))if(g=yield k=>_Yk.sessions.restore(h,k),!_Aw()&&g&&a.push(...g.tab?[g.tab.id]:g.window.tabs.map(k=>k.id)),
++d>=e)break}f([a])});function _fj(a,f){let b=[],d=new _wk;for(let c of _qd(a))0<c&&_Yk.tabs.duplicate(c,d.onReady(e=>b.push(e.id)));d.setCallback(()=>f(b))}function _Ph(a,f=_ay,b={}){let d=new _wk;for(let c of _qd(a)){let e=_Yp[c];0<c&&e&&(b.peek&&(_tr[c]=1),e.active?2==_tr[c]&&_qp(c,e.windowId!=_4t):_Yk.tabs.update(c,{active:!0},d.onReady()))}d.setCallback(()=>f(a))}
function _rl(a,f){let b=new _wk;for(let d of _qd(a))0<d&&_Yk.tabs.discard&&_Yk.tabs.discard(d,b.onReady());b.setCallback(()=>f(a))}function _yy(a,f){_Mh([],f,{url:_qd(a).filter(b=>0<b).map(b=>_zh(_Yp[b])),tabPos:"newWin",incognito:!0})}function _Rh(a,f,b){let d=new _wk;for(let c of _qd(a))0<c&&_Yk.tabs.update(c,{muted:b.mode==_fa?!_Yp[c].mutedInfo.muted:!!b.mode},d.onReady());d.setCallback(()=>f(a))}
function _9f(a,f,b){let d=new _wk;for(let c of _qd(a))0<c&&_Yk.tabs.update(c,{[b.propName]:b.mode==_fa?!_Yp[c][b.propName]:!!b.mode},d.onReady());d.setCallback(()=>f(a))}function _Pe(a,f,b){_9f(a,f,{}.add(b,{propName:"pinned"}))}
function _7f(a,f,b){let d={true:[],false:[]};if(b.inclActTab){var c=_qd(a);for(var e of _yl(c)){let h=_cd[e].activeTab.id;0>c.indexOf(h)&&a.push([h])}}for(var g of _qd(a))c=_Yp[g],0>g||!c||(e=b.mode==_fa?!_go(c):!!b.mode,d[e][c.active?"push":"unshift"](g),e&&c.active&&_Yk.tabs.update(g,{highlighted:!1}));b=new _wk;g={};for(let h of d[!0])c=_Yp[h].windowId,c in g||(g[c]=_cd[c].tabs.some(k=>_go(k))),_Yk.tabs.update(h,{highlighted:!0,active:!g[c]},b.onReady()),g[c]=!0;for(let h of d[!1])_Yk.tabs.update(h,
{highlighted:!1},b.onReady());b.setCallback(()=>f(a))}function _my(a,f,b){let d={},c=[];a[0]&&!_Jw(a[0])&&(a=[a]);for(let e of a){a=[];for(let g of e)f&&d[g]||b&&!b(g)||(d[g]=!0,a.push(g));a.length&&c.push(a)}return c}
let _jj=_cg(function*(a,f,b,d){a=_my(a,!0,e=>"normal"==_Yp[e].window.type);if("newWin"==b.pos)for(let e of a){b=_Yp[e[0]].window.tabs;if(b.length==e.length&&0==_Kf(e,b.map(h=>h.id)).length)continue;b=e.filter(h=>_Yp[h].active)[0];let g=yield h=>_U(e[0],h);1<e.length&&(yield h=>_Yk.tabs.move(e.slice(1),{windowId:g.id,index:-1},h),b&&_Yk.tabs.update(b,{active:!0}))}else{let e=_qd(a);var c=!0;b.refTab&&(c=(yield _ai(d,_gt,b.refTab))[0][0]||_Np,c=!(yield _jg(e,c,b.pos)))}f(c?[]:a)}),_jg=_we(function*(a,
f,b){let d=_Yp[f];if(d&&"normal"==d.window.type){a="after"==b?a:a.slice().reverse();for(let c of a){if(c==f)continue;a=yield g=>_Yk.tabs.get(c,g);if(!a)continue;let e=d.index+("after"==b?1:0);a.windowId==d.windowId&&a.index<e&&--e;d=(yield g=>_Yk.tabs.move(c,{windowId:d.windowId,index:e},g))||d}return!0}});
function _U(a,f){let b=_Yp[a].window;if(1<b.tabs.length){let d=_ay,c={};"normal"==b.state&&(c=b.sc().keep("left","top","width","height"),d=g=>_Yk.windows.update(g.id,c));let e=_Yw(b)||b.state.in("maximized","fullscreen");_Yk.windows.create({tabId:a,focused:e,state:b.state,incognito:b.incognito}.add(c),g=>{d(g);f(g)})}else f(b)}function _Sg(a,f){let b=new _wk;for(let d of _qd(a))_U(d,b.onReady());b.setCallback(()=>f(a))}
let _Ir=_cg(function*(a,f,b,d){function c(h){let k={},n;for(let q of h)h=_Yp[q].windowId,k[h]=(k[h]|0)+1,k[h]<=k[n]||(n=h);return n}var e=_my(a,!0,h=>"normal"==_Yp[h].window.type);let g=_qd(e);if("no"==b.target)_ul(g)||(yield h=>_Yk.tabs.ungroup(g,h));else if("new"==b.target){a=e;for(let h of a)_ul(h)||(yield k=>_Yk.tabs.group({tabIds:h,createProperties:{windowId:c(h)}},k))}else if(a=e,!_ul(g)&&(d=(yield _ai(d,_gt,b.refTab))[0][0],e=_ji(_Yp[d],"groupId"),!b.noNewGrp||0<e))if(yield _jg(g,d,b.target)){let h=
0<e?{tabIds:g,groupId:e}:{tabIds:g.concat(d),createProperties:{windowId:c(g)}};yield k=>_Yk.tabs.group(h,k)}f(a)});
function _zp(a,f){let b,d=[.2,.21,.22,.23,.24,.25,.26,.275,.29,.305,.32,.335,.35,.365,.38,.4,.42,.44,.46,.48,.5,.52,.55,.58,.61,.64,.67,.7,.74,.78,.82,.86,.9,.95,1,1.05,1.1,1.15,1.2,1.27,1.34,1.4,1.47,1.55,1.63,1.7,1.8,1.9,2,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3,3.15,3.3,3.45,3.6,3.8,4,4.2,4.4,4.6,4.8,5,5.25,5.5,5.75,6];for(let c of 0<f?d:d.reverse())if(0<(c-a)*f&&(b=c,0==(f-=f/Math.abs(f))))break;return b}
function _hr(a,f,b=!1){_Yk.tabs.setZoomSettings(a,{scope:b?"per-tab":"per-origin"},()=>_Aw()||_Yk.tabs.setZoom(a,f))}let _Hs={};
function _Ig(a,f,b){for(let d of _qd(a)){if(0>d)if(_Yp[d]&&_Yp[d].windowId==_4t)d=null;else continue;_Yk.tabs.getZoom(d,c=>{c=_yd(c,3);let e=0==b.type?0:"custom"==b.type?b.amount/100:2==Math.abs(b.type)?_fu(c+b.type/2*b.amount/100,.1,8):_zp(c,b.type*(b.steps||1));void 0!==e&&e!=c&&(b.perTab?(_Yk.tabs.onZoomChange.hasListeners()||_Yk.tabs.onZoomChange.addListener(g=>{500>Date.now()-_Hs[g.tabId]||"per-origin"!=g.zoomSettings.scope&&_yd(g.oldZoomFactor,2)==_yd(g.newZoomFactor,2)||(delete _da[g.tabId],
"per-tab"==g.zoomSettings.scope&&(_Yk.tabs.setZoomSettings(g.tabId,{scope:"per-origin"}),_Yk.tabs.setZoom(g.tabId,g.newZoomFactor)))}),_da[d]=e,_Hs[d]=Date.now()):delete _da[d],_hr(d,e,b.perTab))})}f(a)}
function _vd(a,f,b){let d=_lf(_Mo,b.listId,[]);for(let c of d)_Yp[c]||("function"==typeof d.remove?d.remove(c):_Ot("badFavList",{list:d,listType:typeof d,listId:b.listId}));switch(b.oper){case "set":d=_Mo[b.listId]=[];case "add":for(let c of _qd(a))d.add(c);break;case "del":for(let c of _qd(a))d.remove(c)}f(a)}function _Jd(a,f,b,d){_ai(d,_gt,b.tse,a)(f)};
