'use strict';let _lg=_we(function*(a){_Op(a);_Di(a);let d=yield h=>_9i({mouseGest:{},LOCAL:{}},h),e=d.mouseGest||{};_do.setEvtLtnrs($("[name=mouseGest]",a)).append(yield _ud(e)).toggleClass("collapsed",_ul(e));$("[syncSettgs]",a).append(_cy(d.LOCAL));$("[installation]",a).css("display",_9j._Lk(0)?"initial":"none");_Uy&&$("advOpts",a).replaceWith(yield _pa())}),_ud=_we(function*(a){a||(a={});return _Ur`\n ${_pr(a.triggers)}\n <hr>\n ${_6u(a.params)}\n <p>Try your gestures now. <br> Adjust the parameters to obtain the desired accuracy</p>\n <hr>\n ${_ga(a.display)}\n `});
function _pr(a={}){return _Ur`\n <div name=triggers value={}>\n <fldGrp>\n <fldWrap>\n Perform with: ${_kf([..._9j._Vi,["other",{name:"Other"}]].map(([d,e])=>[d,e.name]),a.preset,"preset")} <hw><h h=trig></h></hw>\n </fldWrap>\n ${"other"==a.preset?"<br>":""}\n <fldWrap>\n Timeout: <input type=number name=timeout min=0.2 max=5 step=0.1 value="${a.timeout||1.5}">&nbsp;secs <hw><h h=tOut></h></hw>\n </fldWrap>\n </fldGrp>\n ${"other"==a.preset?_Ur`\n <fldWrap>\n ${_do.make(a.begin,"begin",{title:"Begin gesture with: <h h=/gest/bgn></h>",
extraAttrs:"gestureConf noPreconds"})}\n ${_do.make(a.end,"end",{title:"End gesture with: <h h=/gest/end></h>",extraAttrs:"gestureConf noPreconds"})}\n </fldWrap>\n `:""}\n &nbsp; &nbsp;\n <precondsWrap>\n ${_do.make([{combins:[{eventId:255}],preconds:a.preconds}],"preconds",{extraAttrs:"justPreconds"})}\n <hw><h h=cnd></h></hw>\n </precondsWrap>\n </div>\n `}
function _6u(a={}){return`\n <div name=params value={} popupCntr>\n Gesture precision: ${_tw({4:"<i mouseGestDirs></i>4 directions",8:"<i mouseGestDirs=8></i>8 directions"},"dirPrecision",a.dirPrecision||8,"","number")} <hw><h h=dir></h></hw>\n Stroke size: <input type=number name=stepSize value="${a.stepSize||50}" min=5 step=5> <hw><h h=stp></h></hw>\n <!--Sensibility: <input type=number name=dirChangeSens value="${a.dirChangeSens||2}" min=1 max=10> <hw><h></h></hw> -->\n <!--Segment size: <input type=number name=segmentSize value="${a.segmentSize||
6}" min=1 max=30> <hw><h></h></hw> -->\n <button testGestureBegin>Test gestures</button>\n <button testGestureEnd>End gesture test</button>\n </div>\n `}
function _ga(a={}){a.enabled=null==a.enabled?!0:a.enabled;return`\n <div name=display value={}>\n <label>${_re("enabled",a.enabled,"hard")}Gesture display</label> <hw><h h=dsp></h></hw>\n <span ${a.enabled?"":"greyedout"}>\n Position:\n ${_kf({M:"Mouse",W:"Window",S:"Screen"},a.posRef,"posRef")}\n ${_kf({C:"Center",T:"Top",B:"Bottom"},a.posAnchor,"posAnchor")}\n <hw><h h=pos></h></hw>\n Size: <input type=number name=size value="${a.size||30}" min=10 max=100 step=2> <hw><h h=siz></h></hw>\n Colors: ${_kf({light:"Light",
dark:"Dark"},a.colors,"colors")} <hw><h h=col></h></hw>\n </span>\n </div>\n `}
function _Di(a){let d=new _wk(_cg(function*(e,h){let k=$("[name=toolbarBtns] TBBtnLst",a).html(""),m=0;for(let b of e){e=_Jt(b);var n=_ji(h,b,"icon")||{img:yield _di("tbBtn",e+"","#013379","#ffdc7a")};n=_ep("icon",n,"TBBtn"+b,"tbBtn");k.append(_Ur`\n <TBBtn name=${b}>\n <t>Button ${e}</t>\n Icon: ${n}\n <input type=text name=title value="${_ji(h,b,"title")}" placeholder="Optional title..." autocomplete=off>\n <del button title="Remove"></del>\n </TBBtn>\n ${++m%2?"":"<br>"}\n `);_ji(h,b,"icon")||
n.triggerEvt("change",!0)}}));_Vd()(d.onReady());_ru("toolbarBtns")(d.onReady())}
function _cy(a){let d={"":"Off",true:"On"};80<=_rs&&(d.compress="On (compressed)");a=$(`\n <div><l>Local synchronization:</l> ${_kf({"":"Off",sameBrwr:"Across same browser",allBrwr:"Across all browsers"},a.localSync,"localSync")} <h h=loc></h></div>\n <hr b=4>\n <div><l>Remote synchronization:</l> <c ilnBlk>${_kf(d,a.remoteSync,"remoteSync")} <usg></usg> </c> <h h=rem></h></div>\n `);_Qp($("[name=remoteSync]",a)[0]);return a}
let _Qp=_cg(function*(a){const d=_Yk.storage.sync;let e=100*(yield k=>d.getBytesInUse(k))/d.QUOTA_BYTES|0,h=a.value?`${e}% of ${_5h(d.QUOTA_BYTES)}B`:"";$(a).next().attr("lvl",89<e?"high":75<e?"med":"low").html(h)}),_fi=_we(function*(a,d){var e=yield _ru("trigActList","length");let h=_ji(a,"trigActList","length");if(e&&h){var k=JSON.stringify(yield _Ad())==JSON.stringify(a);if(!k)var m=yield _We(_a("confirmSettgsOvrwrt"),{width:"initial"})}if(k)return"sameSettgs";e="cancel"==m;if(!e)if(h&&"useCurr"!=
m)e=!(yield _Sp(a));else return"currSettgs";e&&(d.value="",$(d).triggerEvt("change",!0))}),_pa=_we(function*(){let a=yield _ru("advOpts");return $(`\n <section name=${"advOpts"} helpCtx=advOpts class=${a?"":"collapsed"}><h1>Advanced Options <btn></btn></h1>\n ${yield _Ls(a)}\n </section>\n `)[0]}),_Ls=_we(function*(a){a={dfltWldcrd:_Ds,ignInjInp:"no",trigRepTime:.6,trigStepTime:1.5}.add(a);let d=[[_Ds,"No wildcard"],[_1o,"On other devices (*)"],[_Ti,"On any device (**)"]],e=yield k=>_Yk.extension.isAllowedIncognitoAccess(k),
h=_id;return`\n <div><l>Trigger's default wildcard:</l> ${_kf(d,a.dfltWldcrd,"dfltWldcrd","number")} <h h=wldcrd></h></div>\n <hr>\n <div><l>Ignore synthetic input:</l> ${_kf({no:"Don't ignore",kbd:"Ignore from keyboard",mse:"Ignore from mouse",all:"Ignore all"},a.ignInjInp,"ignInjInp")} <h h=ignInj></h></div>\n <hr>\n <div tight><l>Trigger repetition timeout:</l> <input type=number name=trigRepTime value=${a.trigRepTime} min=0.1 max=5 step=0.1> &nbsp;secs &nbsp; <h h=repTm></h></div>\n <div><l>Trigger steps timeout:</l> <input type=number name=trigStepTime value=${a.trigStepTime} min=0.1 max=5 step=0.1> &nbsp;secs &nbsp; <h h=stpTm></h></div>\n <hr>\n <div externOpt>\n <st ${h?
"on":"off"}></st>\n <cptn>Local page access is ${h?"ON":"OFF"}</cptn> <h h=fileAcc></h> <br>\n Turn it ${h?"off":"on"} in <a href="${_4a.fileAcc}">this page</a>.\n </div>\n <div externOpt>\n <st ${e?"on":"off"}></st>\n <cptn>Incognito access is ${e?"ON":"OFF"}</cptn> <h h=incgAcc></h> <br>\n Turn it ${e?"off":"on"} in <a href="${_4a.incogAcc}">this page</a>.\n </div>\n `});const _Gh=new _Wf;
function _Op(a){function d(b){"TBBtnInit"==b&&(e(),_Di(a),n=!1)}function e(){_Yk.runtime.onMessageExternal.removeListener(d);_Yk.windows.remove(m||0,_Aw)}_Gu("mouseGest.triggers.preset",(b,c)=>{$("[name=triggers]",a).replaceWith(_pr(_ji(b,...c.slice(0,-1))));_6r(b)});_Gu("mouseGest.display.enabled",(b,c)=>{$("[name=display]",a).replaceWith(_ga(_ji(b,...c.slice(0,-1))))});_Gu("toolbarBtns.*",(b,c)=>{_ve(+c[c.length-1],_ji(b,...c))});let h,k;_Gu("mouseGest.params",(b,c)=>{let f=$("#gestureTestBoard > polyline")[0];
f&&f.points.length&&setTimeout(()=>{_9j._Lk(_fk,!1);k=2;_9j._Lk(_fk,_Ks(f.points[0]));for(let g=1;g<f.points.length;++g)_9j._Lk(_Cf,_Ks(f.points[g]));_9j._Lk(_fk,!1)})});let m,n=!0;$(a).on("click","[installTbBtn]",function(){e();let b=$(this).closest("section").find("TBBtn");for(var c=0;c<_gj.length&&(b.filter(`[name=${c}]`)[0]||c.in(1,2,3,4));++c);let f=_gj[c];f?_Uy?_Mi(["toolbarBtns",c+""],{},0,()=>_Di(a)):_u(_a("addTBBtnMsg",{attrs:n?"":"noReason"}),{width:"initial"},()=>{let g=Math.min(1200,screen.availWidth);
_Yk.windows.create({url:_4a.chromeWS+f,focused:!0,type:"popup",left:_Of+(innerWidth-g)/2|0,top:_tf+(innerHeight-680)/2|0,width:g,height:680},l=>{m=l.id;_Yk.runtime.onMessageExternal.addListener(d)})}):_u(_a("noMoreTBBtns",{maxBtns:_gj.length}),{width:"initial"})}).on("click","[testGestureBegin]",function(){let b=$("<svg id=gestureTestBoard><g></g><polyline/></svg>").appendTo("body")[0],c=b.firstElementChild,f=b.lastElementChild;$(this).closest("[name=params]").addClass("testGesture");$(window).on("mousemove.gestureTest",
function(g){h&&!k&&(_9j._Lk(_Cf,{x:g.originalEvent.screenX,y:g.originalEvent.screenY}),_bf(f,_1a,_Fs))}).on("focus.gestureTest blur.gestureTest",g=>_9j._0d("focus"==g.type?{mouseGest:_Ah("B")}:!1,null));_9j._0d({mouseGest:_Ah("B")},(g,l)=>{if(l.state==_Ah("I"))h=!0,k&&--k||_bf(f,_1a,_Fs,!0),c.innerHTML="";else if(l.state==_Ah("S"))h=!1;else{g=_fu(l.len,10,100);let p=_7p(l);l=45*(_Lj(l.dir)-1);c.insertAdjacentHTML("beforeend",`<path d="M-7,7 L0,0 L7,7 M0,5 L0,${g}" transform="translate(${p.x} ${p.y-
g}) rotate(${l} 0 ${g})"/>`)}})}).on("click","[testGestureEnd]",function(){$("#gestureTestBoard").remove();$(this).closest("[name=params]").removeClass("testGesture");$(window).off(".gestureTest");_9j._0d(!1);h=!1}).on("dblclick","TBBtn del",function(){_Mi(_1j(this),void 0,0,()=>_Di(a))}).on("click","section > h1 btn",_cg(function*(){let b=$(this).closest("section");if(b.hasClass("collapsed")){let c={mouseGest:_ud,advOpts:_Ls},f=b.attr("name");$("> :not(h1)",b).remove();b.append(yield c[f](yield _ru(f)))}else _Mi(_1j(this),
null,0);b.toggleClass("collapsed")})).on("change","[name=localSync]",_cg(function*(){if(this.value){let b="sameBrwr"==this.value;_Gh.clear();yield _Gh.wait();let c=yield _9j._6j(b);if(yield _fi(c,this))yield _Ee("add"),yield _9j._qj(b)}else yield _Ee("del");_9j._Gi(this.value)})).on("change","[name=remoteSync]",_cg(function*(b,c){if(this.value&&"dontSync"!=c){yield _9j._ce();let [g,l]=yield _9j._bp();var f=yield _fi(g,this);80<=_rs&&!f&&l&&"true"==this.value&&(this.value="compress",$(this).triggerEvt({change:"dontSync"},
!0))}_9j._Wh(this.value);("currSettgs"==f||"sameSettgs"==f)&&(b=yield _9j._Pa())&&b.size>b.quota&&(_u(`\n Your settings require <b>${_5h(b.size,4)}B</b> of storage which exceeds the maximum of <b>${_5h(b.quota)}B</b>\n allowed by your browser's sync service. <hr b=2>\n Remote synchronization won't be possible. ${"compress"==this.value?"":'Try enabling "compressed" mode.'}\n `,{type:"warning"}),this.value="",$(this).triggerEvt("change",!0));_Qp(this)})).on("click","[exportToFile]",()=>{let b=`${_Bj.alias} settings (${_8h(new Date,
"Y-M-D")}).${_Lu}`;_xf(c=>_2o(b,JSON.stringify(c)))}).on("click","[importFromFile]",_cg(function*(){let b=yield _Fj(_Wd,"text");_kp(b)})).on("click","[openSttgsFile]",_cg(function*(){let b=yield _xg("",_to);b&&_mt(b)})).on("click","[uninstall]",()=>_ei()).on("click","advOpts",_cg(function*(){let b=yield _pa();b.style.cssText="opacity: 0; transform: scaleY(0); ";$(this).replaceWith(b);b.scrollIntoView({behavior:"smooth"});yield c=>_ed(c);b.style.cssText="transform-origin: top; transition: 0.6s"})).on("change",
function(b){if(!$(b.target).parent().closest("[DataModule]")[0]){let c=_1j(b.target),f=c.join("."),g=_fw(b.target);"mouseGest.triggers.preconds"==f&&(g=g[0].preconds);b="advOpts"==c[0]||f.endsWith(".timeout")||$(b.target).is("triggers")||f.startsWith("mouseGest.display.")&&!f.endsWith(".enabled")?400:0;_Mi(c,g,b,()=>_Gh.send())}})}
let _ei=_cg(function*(){if(_9j._Lk(0)){if(yield _Ng("","\n Once the native component is uninstalled, the extension will no longer work. <hr b=2>\n To make it work again, you'll have to re-install the native component by <br> reloading this page. <hr b=2>\n Do you want to uninstall now?\n ",{width:"initial"})){_Lg();var a=yield _9j._iw("dir /B *.exe",".",!0);a=[...new Set(a.stdout.trim().split(/\n+/))].map(d=>{d=(d.match(/^[a-z]+/i)||[])[0];return"AutoCtrl"!=d?_ji(_Er,d,"name"):""}).filter(d=>d);if(a.length&&
(_Lg(!1),!(yield _Ng("",`\n The native component is also being used by the following extensions: <hr b=2>\n ${a.map(d=>`<li><b>${d}</b></li>`).join("")} <hr b=4>\n If you uninstall now, those extensions will stop working too. <hr b=2>\n Continue?\n `,{yes:"Yes, uninstall anyway",no:"Cancel",icon:"info"}))))return;_Lg();a=`"%tmp%\\${_or}"`;yield _9j._iw(`copy /Y ${_ne} /B ${a} && cd .. && ${a} /noConfirm | more & del /F /Q ${a}`);setTimeout(()=>_Lg(!1),2E3)}}else _u("The native component is not installed.",
{type:"error"})});
