'use strict';let _2y,_zw,_Wi,_Fk=!0;var _Rf=_we(function*(a=!1){if(a||_Fk)yield b=>_Fu(b),_wd(),_Fk=!1});function _wd(){_kg=_hu=_Bk=_1i=_Kt=null;_Jr={}}
let _Pw=_cg(function*(a=0,b=!1){const c=_2y[0];yield _za(a);if(c==_2y[0]){if(b)if("runScript"==_Wi){if(a=yield h=>_Uk(h),_Ot("stuckAction",{action:"runScript",answer:a}),c==_2y[0]&&(_2y.length=1,!a))return}else _Ot("stuckAction",{action:_Wi});_2y.shift();_6y()}}),_6y=_cg(function*(a,b=null){if(a)a:if(_2y.push([a,b]),1<_2y.length){b=4;if("sendInput"==_Wi){a=_ji(_ek,a,0,"sequence",0)||{};if("stopSendInput"==a.action){_ks([],_ay,a.params||{});_2y.shift();break a}b=8}else"wait"==_Wi&&(b=30);_2y.length==
b&&_Pw(1200,!0);return}for(_Fk=!0;_2y.length;){const c=_2y[0];[a,b]=c;(a=_ek[a])&&(yield _rf(a,null,b));if(c!=_2y[0])break;_2y.shift()}}),_Da=0;
var _rf=_we(function*(a,b,c){c||(c=_Ai());let h=0;a:for(let e of a){yield _Rf();if(h++||!b){_se=null;let f;"hoveredTabs"==e.targets&&e.sequence&&1==e.sequence.length&&(a=e.sequence[0],f="object"==typeof _w(a.action,a.params));b=e.targets&&!f?yield _ai(c,_gt,e.targets):_Np?[[_Np]]:[]}b:for(let {action:f,params:k}of e.sequence||[]){yield _Rf();let l=_w(f,k);if("object"==typeof l)b=yield _rf(l,null,c);else{_Wi=f;_se&&(b.forEach(d=>{for(let g=0;g<d.length;++g)_se[d[g]]&&(d[g]=_se[d[g]])}),_se=null);try{let d=
yield g=>l(b,g,k||{},c);if(!_Jw(d)){if("inner"==d.break)break b;if("outer"==d.break)break a}b=d}catch(d){_Ot("error",{action:f,stack:d.stack,params:"saveUrl"==f?k:void 0})}_Fk=!0}}}return b});
_Du.action={activateTabs:{name:"Activate tabs",grp:"tab",h:1,value:_Ph},reloadTabs:{name:"Reload tabs",grp:"tab",value:_Xs},goBackTabs:{name:"Go back",grp:"tab",value:_Is},goForwardTabs:{name:"Go forward",grp:"tab",value:_Zi},goUpURL:{name:"Go upper URL",grp:"tab",h:1,value:_1r},loadUrls:{name:"Open URL",grp:"tab",h:1,value:_Mh},highlightTabs:{name:"Select tabs",grp:"tab",h:1,value:_7f},pinTabs:{name:"Pin tabs",grp:"tab",value:_Pe},zoomTabs:{name:"Zoom tabs",grp:"tab",value:_Ig},muteTabs:{name:"Mute tabs",
grp:"tab",h:1,value:_Rh},moveTabs:{name:"Move tabs",grp:"tab",h:1,value:_jj},detachTabs:{name:"Detach tabs",grp:"tab",h:1,value:_Sg},groupTabs:{name:"Group tabs",grp:"tab",h:1,value:_Ir},duplicateTabs:{name:"Duplicate tabs",grp:"tab",h:1,value:_fj},openInIncognito:{name:"Open in incognito",grp:"tab",h:1,value:_yy},closeTabs:{name:"Close tabs",grp:"tab",h:1,value:_Zj},undoClose:{name:"Reopen tabs",grp:"tab",h:1,value:_3j,perms:"ses"},unloadTabs:{name:"Unload tabs",grp:"tab",h:1,value:_rl},favoriteTabs:{name:"Favorite tabs",
grp:"tab",h:1,value:_vd},alterTgtTabs:{name:"Alter target tabs",grp:"",value:_Jd},focusWin:{name:"Focus",grp:"win",h:1,value:_Ny},moveResizeWins:{name:"Move/Resize",grp:"win",h:1,value:_Pt},fitWinsToGrid:{name:"Fit to grid",grp:"win",h:1,value:_Pt},tileWins:{name:"Tile",grp:"win",h:1,value:_ft},minimizeWins:{name:"Minimize",grp:"win",value:_sk(_Hr)},maximizeWins:{name:"Maximize",grp:"win",value:_sk(_tp)},restoreWins:{name:"Restore",grp:"win",h:1,value:_ci},fullscreenWins:{name:"Fullscreen",grp:"win",
value:_4d},hideWins:{name:"Hide",grp:"win",h:1,value:_ar},scrollWins:{name:"Scroll",grp:"win",h:1,value:_0g},topmostWins:{name:"Stay on top",grp:"win",h:1,value:_sk(_si)},sendWinsToBottom:{name:"Send to bottom",grp:"win",h:1,value:_jk},openBookmarks:{name:"Open bookmarks",grp:"bmrk",h:1,value:_Mh,perms:"bkm"},bookmarkTabs:{name:"Bookmark tabs",grp:"bmrk",h:1,value:_Vu,perms:"bkm"},bookmarkUrls:{name:"Bookmark URL",grp:"bmrk",h:1,value:_Vu,perms:"bkm"},openMenu:{name:"Open menu",grp:"menu",h:1,value:_Jj},
closeMenu:{name:"Close menu",grp:"menu",value:_Oa},moveSelectMark:{name:"Move item mark",grp:"menu",h:1,value:_eu},selectMarkedItem:{name:"Select menu item",grp:"menu",h:1,value:_2h},clpbrdCut:{name:"Clipbrd cut",grp:"clbrd",h:1,value:_gp(_kt)},clpbrdCopy:{name:"Clipbrd copy",grp:"clbrd",h:1,value:_gp(_yj)},clpbrdPaste:{name:"Clipbrd paste",grp:"clbrd",h:1,value:_gp(_Ky)},clpbrdPut:{name:"Clipbrd put",grp:"clbrd",h:1,value:_Hg()},copyElemUrl:{name:"Copy hovered URL",grp:"clbrd",h:1,value:_Ut,perms:"hst"},
copyLinks:{name:"Copy selected URLs",grp:"clbrd",h:1,value:_E},extractURLs:{name:"Extract URLs",grp:"clbrd",h:1,value:_Hp},txtToUrl:{name:"Text to URL",grp:"clbrd",h:1,value:_ia},delDupLines:{name:"Erase dup. lines",grp:"clbrd",h:1,value:_Yu},clpbrdDiscard:{name:"Discard",grp:"",h:1,value:_ay},setVolume:{name:"Change volume",grp:"sys",h:1,value:_5o},showDesktop:{name:"Show desktop",grp:"sys",h:1,value:_Us},setMonBright:{name:"Screen brightness",grp:"sys",h:1,value:_8k},screenSaver:{name:"Screen saver",
grp:"sys",h:1,value:_li("scrSvr")},setMonPower:{name:"Turn off screen",grp:"sys",h:1,value:_li("monOff")},brkActSeq:{name:"Continue chain if",grp:"exec",h:1,value:_8e},setSwtchSt:{name:"Set switch state",grp:"exec",h:1,value:_ui},wait:{name:"Wait",grp:"exec",h:1,value:_Ga},saveUrl:{name:"Save URL",grp:"other",h:1,value:_fp},playAudio:{name:"Play audio",grp:"other",h:1,value:_7r},insertText:{name:"Insert text",grp:"other",h:1,value:_Hg(!0)},sendInput:{name:"Synthesize input",grp:"other",h:1,value:_ss},
stopSendInput:{name:"Stop synth input",grp:"other",h:1,value:_ks},runCommand:{name:"Open file/program",grp:"other",h:1,value:_Yg},runScript:{name:"Run script",grp:"other",h:1,value:_To,perms:"hst"},screenShot:{name:"Take screenshot",grp:"",h:1,value:_ay},openNTP:{name:"Open new tab",h:1,value:{gener:_c}},goBack:{name:"Back",h:1,value:[{sequence:[{action:"goBackTabs"}],targets:"currentTab"}]},goForward:{name:"Forward",h:1,value:[{sequence:[{action:"goForwardTabs"}],targets:"currentTab"}]},reload:{name:"Reload",
h:1,value:[{sequence:[{action:"reloadTabs"}],targets:"currentTab"}]},zoomIn:{name:"Zoom in",h:1,value:[{sequence:[{action:"zoomTabs",params:{type:1,steps:1}}],targets:"currentTab"}]},zoomOut:{name:"Zoom out",h:1,value:[{sequence:[{action:"zoomTabs",params:{type:-1,steps:1}}],targets:"currentTab"}]},duplicate:{name:"Duplicate tab",h:1,value:[{sequence:[{action:"duplicateTabs"}],targets:"currentTab"}]},detach:{name:"Detach tab",h:1,value:[{sequence:[{action:"detachTabs"}],targets:"currentTab"}]},switchPrev:{name:"Switch to previous tab",
h:1,value:[{sequence:[{action:"activateTabs"}],targets:"prevUsedTab"}]},switchLeft:{name:"Switch to left tab",value:[{sequence:[{action:"activateTabs"}],targets:"leftTabWrap"}]},switchRight:{name:"Switch to right tab",value:[{sequence:[{action:"activateTabs"}],targets:"rightTabWrap"}]},switchLeftmost:{name:"Switch to leftmost tab",value:[{sequence:[{action:"activateTabs"}],targets:"firstTab"}]},switchRightmost:{name:"Switch to rightmost tab",value:[{sequence:[{action:"activateTabs"}],targets:"lastTab"}]},
pin:{name:"Pin tab",h:1,value:[{sequence:[{action:"pinTabs",params:{mode:_fa}}],targets:"currentTab"}]},mute:{name:"Mute tab",h:1,value:[{sequence:[{action:"muteTabs",params:{mode:_fa}}],targets:"currentTab"}]},close:{name:"Close tab",h:1,value:{gener:_Vk}},closeLefts:{name:"Close left tabs",h:1,value:[{sequence:[{action:"closeTabs"}],targets:"allLeftTabs"}]},closeRights:{name:"Close right tabs",h:1,value:[{sequence:[{action:"closeTabs"}],targets:"allRightTabs"}]},closeOther:{name:"Close other tabs",
h:1,value:[{sequence:[{action:"closeTabs"}],targets:"otherTabs"}]},closeWin:{name:"Close window",h:1,value:[{sequence:[{action:"closeTabs"}],targets:"currWinTabs"}]},reopen:{name:"Reopen closed tab",h:1,value:[{sequence:[{action:"undoClose"}]}],perms:"ses"},openElemUrl:{name:"Open element URL",h:1,value:{gener:_yk},perms:"hst"},saveElemUrl:{name:"Save element URL",h:1,value:{gener:_Ci},perms:"hst"}};
